### ISSUE TITLE
DEAD OR ALIVE Xtreme 3 Scarlet

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#161]
#### Current on `master` :

* Build Version : 1.0.2584

```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.ISelfController: 91
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Time.IStaticService: 20
```

Implement that, and then crash:
```
CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: c004481d (NvHostChannelIoctl)
   at Ryujinx.HLE.HOS.Services.Nv.NvHostChannel.NvHostChannelIoctl.ProcessIoctl(ServiceCtx context, Int32 cmd) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Services\Nv\NvHostChannel\NvHostChannelIoctl.cs:line 42
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Acc.IAccountService: 140
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Acc.IAccountService: 150
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.IRequest: 21
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ns.IAddOnContentManager: 8
```

Implement that, and then crash:
```
GetAudioRendererWorkBufferSize: Library Revision 0x35564552 is not supported!
ServiceAm SetTerminateResult: Result = 0x00000499 (2153-0002).
Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00175ebc nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, std::__va_list)
   sdk:0x00175f80 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, char const*, ...)
   sdk:0x0008a928 nn::audio::GetAudioRendererWorkBufferSize(nn::audio::AudioRendererParameter const&)
   main:0x004b1950 Sub00000000084b5950
   main:0x004b1560 Sub00000000084b5560
   main:0x004b0f08 Sub00000000084b4f08
   main:0x005ac294 Sub00000000085b0294
   main:0x006200d0 Sub00000000086240d0
   main:0x0061ff78 Sub0000000008623f78
   main:0x0061ec54 Sub0000000008622c54
   main:0x003571a4 Sub000000000835b1a4
   main:0x00364e2c Sub0000000008368e2c
   main:0x0029777c Sub000000000829b77c
   main:0x002ee5c8 Sub00000000082f25c8
   sdk:0x00320eb4 nn::os::detail::CallFiberFunction(nn::os::FiberType* (*)(void*), void*)
```

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/615
- https://github.com/Ryujinx/Ryujinx/issues/616
- https://github.com/Ryujinx/Ryujinx/issues/666
- https://github.com/Ryujinx/Ryujinx/issues/667
- https://github.com/Ryujinx/Ryujinx/issues/668
- https://github.com/Ryujinx/Ryujinx/issues/669

**Comment by zemzema** [comment]
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3234197/Ryujinx.log)

Status is nothing for version 1.0.2651

**Comment by SeraUX** [comment]
## DEAD OR ALIVE Xtreme 3 Scarlet

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4740

Game crashes on boot with an missing service error

```
00:00:25.618 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0030a0c8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 12ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x003098e4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IRequest, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IRequest>::_nn_sf_sync_GetAppletInfo(nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::OutBuffer const&, unsigned int)
   sdk:0x0030777c nn::nifm::detail::RequestClient::PrepareLibraryApplet(nn::applet::LibraryAppletHandle*)
   sdk:0x0030cf24 nn::nifm::PrepareHandlingNetworkRequestResult(nn::nifm::RequestHandle, nn::applet::LibraryAppletHandle*)
   sdk:0x0030e9c8 nn::nifm::NetworkConnection::HandleNetworkRequestErrorResult()
   sdk:0x0030d6f4 nn::nifm::HandleNetworkRequestErrorResult()
   main:0x0065a208 Sub000000000865e208
   main:0x005af784 Sub00000000085b3784
   sdk:0x0031d4d8 Sub000000000b91e4d8
   sdk:0x00321938 Sub000000000b922938
   ??? Sub0000000000000000

Buffer Information:
        ReceiveBuff:
        Position: 0x00000011eb5a3e1c Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   01 00 14 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  15 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 01 00 00 00 04 00   ················
00000030   00 00 04 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Log file :

[doax3s.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4813748/doax3s.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Seker-0** [comment]
## DEAD OR ALIVE Xtreme 3 Scarlet

#### Game Update Version : 1.0.5 / USA / 56DLC

#### Current on `master` : 1.0.4847

This game can be fully played. Sometimes the sound will be slower than the picture and the text is still blinking randomly.
game will randomly crash into some missions. But there are no errors in the logs file

#### Hardware Specs :

GPU : 1060
CPU : I5 8400
RAM : 16GB

#### Screenshots :

![bandicam 2020-07-06 06-36-00-432](https://user-images.githubusercontent.com/35269098/86545557-df71e780-bf59-11ea-8a1c-8d297f3f9dac.jpg)
![bandicam 2020-07-06 06-36-07-703](https://user-images.githubusercontent.com/35269098/86545560-e3056e80-bf59-11ea-8e06-1843202e17dc.jpg)
![bandicam 2020-07-06 06-36-16-011](https://user-images.githubusercontent.com/35269098/86545563-e6005f00-bf59-11ea-851e-6a9c3ade4da0.jpg)
![bandicam 2020-07-06 06-37-35-984](https://user-images.githubusercontent.com/35269098/86545574-ec8ed680-bf59-11ea-8039-cbbc7c19515f.jpg)
![bandicam 2020-07-06 06-37-39-319](https://user-images.githubusercontent.com/35269098/86545578-f0225d80-bf59-11ea-89eb-785eceeb8ddc.jpg)
![bandicam 2020-07-06 06-38-26-216](https://user-images.githubusercontent.com/35269098/86545585-f87a9880-bf59-11ea-9c54-f659f316ba4b.jpg)
![bandicam 2020-07-06 06-38-32-031](https://user-images.githubusercontent.com/35269098/86545588-fadcf280-bf59-11ea-88ba-ca623c5c2a27.jpg)
![bandicam 2020-07-06 06-39-19-844](https://user-images.githubusercontent.com/35269098/86545592-003a3d00-bf5a-11ea-8b80-db96d19061fc.jpg)
![bandicam 2020-07-06 06-40-49-248](https://user-images.githubusercontent.com/35269098/86545594-06301e00-bf5a-11ea-8945-c455852d0d1b.jpg)
![bandicam 2020-07-06 06-40-22-182](https://user-images.githubusercontent.com/35269098/86545596-08927800-bf5a-11ea-90cf-f2bbeadc2842.jpg)
![bandicam 2020-07-06 06-41-28-767](https://user-images.githubusercontent.com/35269098/86545603-1516d080-bf5a-11ea-868b-62295835ee90.jpg)

#### Outstanding Issues :


#### Logs : 

[DOAX3S.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4876163/DOAX3S.log)

**Comment by EmulationFanatic** [comment]
Updated. Thanks!

**Comment by mstreurman** [comment]
The game indeed starts without issue now... I'm running Ryujinx 1.0.6840 and DOAX3S 1.06... the biggest problem I can currently see is that the sky is pink where it should be blue...

**Comment by EmulationFanatic** [comment]
@Cronos-0 can you re-test?

**Comment by mstreurman** [comment]
After a little bit more testing I found out that it gets less pink during the evening in the game, if I compare it to YUZU, the color it gets in the evening is the correct color for the evenings. YUZU also has the daytime color blue as it should be, but the performance in the volleyball games is way too low in YUZU.

**Comment by jojorne** [comment]
Update: The pink sky problem has been fixed as of version 1.0.6905.

**Comment by mstreurman** [comment]
Tested and confirmed fixed pink skies during the day.

**Comment by jojorne** [comment]
I want to add that this is the first emulator of a portable video game console that the doax series photo mode fully works!!!

**Comment by mstreurman** [comment]
Game started crashing randomly at loading screens and tutorial screens now as of version 1.0.6906, music keeps playing but nothing else happens, all animations stop and no button presses are accepted anymore. Stopping the game using the Stop emulation button does still work.
Purged Shader Cache and PPTC. Still the same issue. This is running the game version 1.0.6 + 52 DLC's. 

Log from crashes all end with this:
00:00:38.961 |I| HLE.OsThread.10 ServiceNv Create: Created map 67 with size 0x00001000!
00:00:38.961 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 67!
00:00:46.170 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x10bc575000, size 0x1e3000) failed!
00:01:01.949 |I| Ptc Save: Saved Profiling Info (size: 78940 bytes, profiled functions: 24333).
00:01:41.923 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.

**Comment by jojorne** [comment]
@mstreurman Yeah, I think it was caused by the [Implemented a multi-level function table](https://github.com/Ryujinx/Ryujinx/pull/2228).

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Nickcz91** [comment]
I'm Running Version 1.0.0 and 1.0.5 on Ryujinx 1.0.6906 and im still getting constant crashes after day 1 ingame

Windows 10
CPU: 8700k
GPU: NVIDIA GTX 1080
RAM: 32GB

**Comment by Nickcz91** [comment]
[Log](https://pastebin.com/gtHS9CNC) if that helps

**Comment by mstreurman** [comment]
> [Log](https://pastebin.com/gtHS9CNC) if that helps
> 
> seems like the same issue mstreurman has to me

No to me is seems completely random at random times during loading screens and tutorial screens, if I don't immediately press anything it just stops responding to any inputs. Sometimes I can't even enter the game and it stops loading at one of the splash screens at the start of the game, other times I can play for 5 minutes or even half an hour... but I will get a crash and it is always during a loading screen with the error message every time that copy/pasted in my previous post.

**Comment by jojorne** [comment]
Can anyone else confirm the shadow issue where some hairs do not render shadow?

**Comment by mstreurman** [comment]
> Can anyone else confirm the shadow issue where some hairs do not render shadow?

You are correct that the hair doesn't render shadow... But looking at the game on my Switch... it doesn't render there either. Just to doublecheck I checked video's of gameplay on Youtube, and guess what... the shadows as they are right now in Ryujinx are working as intended :)

**Comment by alexwpi** [comment]
Fully playable for me.

Constant 30fps build 1.0.6910
I5 10400F / GF 970SC

Game version 1.0.6 all dlc
docked x2

https://youtu.be/ru9kNAObJXI

![imagem_2021-06-10_214921](https://user-images.githubusercontent.com/85715907/121614741-b6918680-ca35-11eb-8c48-60c199921198.png)
![imagem_2021-06-10_215044](https://user-images.githubusercontent.com/85715907/121614811-e8a2e880-ca35-11eb-82e8-c6d09c5d0ac4.png)
![imagem_2021-06-10_215201](https://user-images.githubusercontent.com/85715907/121614896-16882d00-ca36-11eb-828b-dfe7c5c598a0.png)
![imagem_2021-06-10_215344](https://user-images.githubusercontent.com/85715907/121615028-53ecba80-ca36-11eb-8a4e-051a133341d1.png)
![imagem_2021-06-10_220715](https://user-images.githubusercontent.com/85715907/121615867-37518200-ca38-11eb-8a18-1ea62f0be57e.png)

**Comment by MattPonton** [comment]
Steam Deck
(AMD GPU)

Menus generally render fine without issue. However, lighting/textures don't display when "in-game" like at pool side or in a volleyball match. Anywhere the character is being rendered on screen.

Also when in a volleyball match FPS can drop to around 15-20 FPS. All other modes seem to render at 30 FPS.

![image](https://user-images.githubusercontent.com/45347806/164563992-2d8477d2-8fc4-484d-a801-1d66084e2b2e.png)

**Comment by TheNamelessWonderer** [comment]
Game doesn't work at all for me with 1.1.183. The game just freezes with 0 FPS and the sound keeps playing.
![image](https://user-images.githubusercontent.com/56267607/180615323-7c1a90ed-1e72-4980-a81c-8a5e1e0e1cfb.png)
[Ryujinx_1.1.183_2022-07-23_17-49-32.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9174230/Ryujinx_1.1.183_2022-07-23_17-49-32.log)
