### ISSUE TITLE
Luigi's Mansion 3

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx-Games-List#207]
#### Status @ [`Ryujinx/cbbbf175`](https://github.com/Ryujinx/Ryujinx/tree/cbbbf175):

![dotnet_KJWnK9bjLJ](https://user-images.githubusercontent.com/1518948/68062536-0e96e000-fd5f-11e9-8200-eb65b224e429.png)

#### Pull requests needed :

- [Implement a rudimentary applets system (#804)](https://github.com/Ryujinx/Ryujinx/pull/804)

#### Outstanding Issues:

- 

#### Screenshots :

![dotnet_KJWnK9bjLJ](https://user-images.githubusercontent.com/1518948/68062575-4bfb6d80-fd5f-11e9-9f6e-1a301757b618.png)

![dotnet_LSJPUQvgLb](https://user-images.githubusercontent.com/1518948/68062619-8d8c1880-fd5f-11e9-9044-63a3c4f5f570.png)

![dotnet_DRvmfXqLGM](https://user-images.githubusercontent.com/1518948/68062581-56b60280-fd5f-11e9-9c4e-49f94e8cb591.png)

![dotnet_MiQJnn77aR](https://user-images.githubusercontent.com/1518948/68062605-836a1a00-fd5f-11e9-89de-e472a56c8765.png)

**Comment by AcK77** [comment]
Updated

**Comment by Thog** [comment]
This screenshot was posted by a user running the following NVIDIA hardware and driver version: NVIDIA Corporation GeForce RTX 2060/PCIe/SSE2 (4.6.0 NVIDIA 445.75)

Flickering seems to be present.

![image](https://user-images.githubusercontent.com/1760003/77593814-2aa94280-6ef5-11ea-8d2d-3790c95a686d.png)

Full logs: [Ryujinx_2020-03-25_23-55-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4384172/Ryujinx_2020-03-25_23-55-08.log)

**Comment by djwarcr** [comment]
Hi,
Today's update 1.0.4224 added a new glitch when pausing the game, glitch was not presented in previous versions of Ryu.
Please help make this game more compatible

![Ryu 4224](https://user-images.githubusercontent.com/63897649/79630610-0c0f2380-8110-11ea-81e2-2964f9c4e3fa.JPG)

**Comment by verysecureyes** [comment]
Audio is one of the worst out of all of the switch games. Constant stuttering with audio.

**Comment by EmulationFanatic** [comment]
## Luigi's Mansion 3

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4880

- Intro cutscene is choppy and somewhat slow, but watchable. 
- Through the intro and into the in-game portion, graphics look good but not quite perfect. Doesn't clear shadow maps correctly.
- FPS averages around 14, but the game can still be played through.

#### Hardware Specs : 

##### CPU: i5-6600K
##### GPU: NVIDIA GTX 1080
##### RAM: 16GB

#### Screenshots :

![2020-07-10 10_34_43-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179053-5a5d3a00-c29b-11ea-958b-5467ff35dbeb.png)
![2020-07-10 10_36_05-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179056-5af5d080-c29b-11ea-93f1-c5fc1bc2da3b.png)
![2020-07-10 10_36_21-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179080-647f3880-c29b-11ea-8241-a9b0ef241ec6.png)
![2020-07-10 10_37_22-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179100-6a751980-c29b-11ea-8fd1-554af9ecf16d.png)
![2020-07-10 10_38_00-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179127-752fae80-c29b-11ea-9a18-440f4536b411.png)
![2020-07-10 10_41_22-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179148-7cef5300-c29b-11ea-9b0b-31c7e1d6853d.png)
![2020-07-10 10_42_12-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179167-87a9e800-c29b-11ea-9716-447b51cac7eb.png)
![2020-07-10 10_46_12-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179186-91335000-c29b-11ea-9cd5-093113902324.png)
![2020-07-10 10_47_48-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179213-9a242180-c29b-11ea-9a1d-90f1b76596d7.png)
![2020-07-10 10_48_21-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179240-a314f300-c29b-11ea-938f-03ca61045a99.png)
![2020-07-10 10_49_14-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179260-ac05c480-c29b-11ea-9de1-4873bacb093b.png)
![2020-07-10 10_49_49-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179272-b32cd280-c29b-11ea-842e-86db27bd20ea.png)
![2020-07-10 10_50_00-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179283-b9bb4a00-c29b-11ea-8840-71551367737a.png)
![2020-07-10 10_50_06-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179304-c17aee80-c29b-11ea-9c51-425112489e62.png)
![2020-07-10 10_50_23-Ryujinx 1 0 4880 - Luigi's Mansion 3 v1 0 0 (0100DCA0064A6000) (64-bit)](https://user-images.githubusercontent.com/62343878/87179328-c9d32980-c29b-11ea-9ead-4ad7aa184cfb.png)

#### Log file :

[LM3.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4904427/LM3.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by hefang0918** [comment]
Game Update Version : 1.0.0

Current on master : 1.0.5155

1. When going to the B2 floor, in the elevator, the ryujinx Emulator crash
2. The console code is also at rest

Hardware Specs :

CPU: I7-4790

GPU: NVIDIA GTX 1060 6G

RAM: 16GB

Screenshots :
![001](https://user-images.githubusercontent.com/69452926/89765095-3ace6100-db28-11ea-99ca-fa0a8fb242be.jpg)

**Comment by fifihomeless** [comment]
me too, I don't know how to solve this problem. Anyone help us, please?

**Comment by pcca-matrix** [comment]
same for me on master 1.0.5485 , game update 1.4.0 or 1.0.0
When going to the B2 floor, the elevator will lower indefinitely.
background music and elevator sound continue but emu is locked.

**Comment by albfan** [comment]
That is a known problem for game itself, fixed on update 1.2.0

**Comment by albfan** [comment]
Older versions of Ryujinx should allow to continue

https://ci.appveyor.com/project/gdkchan/ryujinx/builds/34061417/artifacts

On recent versions the only way to make it work is to disable FastFP

https://github.com/Ryujinx/Ryujinx/blob/master/ARMeilleure/Optimizations.cs#L7

```
diff --git a/ARMeilleure/Optimizations.cs b/ARMeilleure/Optimizations.cs
index fbbbfdb2..93c5adbb 100644
--- a/ARMeilleure/Optimizations.cs
+++ b/ARMeilleure/Optimizations.cs
@@ -4,7 +4,7 @@ namespace ARMeilleure
 {
     public static class Optimizations
     {
-        public static bool FastFP { get; set; } = true;
+        public static bool FastFP { get; set; } = false;
 
         public static bool UseSseIfAvailable       { get; set; } = true;
         public static bool UseSse2IfAvailable      { get; set; } = true;
```

@jduncanator seems related with https://github.com/Ryujinx/Ryujinx/pull/1335

Attached to saved state games for game update 1.4.0 to test:

[lm3-before-go-b2-floor.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5367058/lm3-before-go-b2-floor.zip)
[lm3-after-b2-floor.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5367059/lm3-after-b2-floor.zip)

**Comment by albfan** [comment]
A narrow version of the patch fixes it while keeping the game fast

```
diff --git a/ARMeilleure/Instructions/InstEmitSimdArithmetic.cs b/ARMeilleure/Instructions/InstEmitSimdArithmetic.cs
index 0d417f70..eb532658 100644
--- a/ARMeilleure/Instructions/InstEmitSimdArithmetic.cs
+++ b/ARMeilleure/Instructions/InstEmitSimdArithmetic.cs
@@ -380,7 +380,7 @@ namespace ARMeilleure.Instructions
 
         public static void Faddp_V(ArmEmitterContext context)
         {
-            if (Optimizations.FastFP && Optimizations.UseSse2)
+            if (false && Optimizations.UseSse2)
             {
                 EmitSse2VectorPairwiseOpF(context, (op1, op2) =>
                 {
```

After apply:

    dotnet publish -c Release --output /path/to/ryujinx/

**Comment by Djipi71** [comment]
Luigi's Mansion : All 1.0 / 1.2 / 1.21 Test

There is a texture error , the texture not appear , only transparent.

Same problem appear on : Museum floor / Elevator ground / Music Floor / Pyramid floor  and final battle arena
They look black but on music floor we see object behind the ground so it's transparent.

![Sans titre-1](https://user-images.githubusercontent.com/35375131/99387380-2db5d080-28d4-11eb-8660-7f543acea494.png)

**Comment by Ghostotakoi** [comment]
**IDK if this is reported already but the resolution scaling make some artifacts in the game, mostly on walls, floors, fog, lights**
![Screenshot - 26_02_2021 , 09_27_24 p  m _compressed](https://user-images.githubusercontent.com/20958581/109375374-47c75d80-788a-11eb-9415-2468fecc50d3.jpg)

**Also, I don´t think is related but reflections are broken**
![Screenshot - 26_02_2021 , 09_18_06 p  m _compressed](https://user-images.githubusercontent.com/20958581/109375415-937a0700-788a-11eb-8c21-35a1ac28e3ce.jpg)
![Screenshot - 26_02_2021 , 09_27_24 p  m _compressed](https://user-images.githubusercontent.com/20958581/109375416-94ab3400-788a-11eb-9364-964d90e7dba3.jpg)

**and some times this happen when you enter some doors.**
![Screenshot - 26_02_2021 , 09_28_08 p  m _compressed](https://user-images.githubusercontent.com/20958581/109375445-befcf180-788a-11eb-8615-3df47cba82a5.jpg)

**Comment by Omar-Hegab** [comment]
I think that the issue regarding Shadow Maps reappeared as it was fixed before.
![Annotation 2021-10-28 021539](https://user-images.githubusercontent.com/73315805/141355776-bbea7da4-50b7-4eca-a2cc-e6c0bda53c98.png)
![Annotation 2021-10-28 021607](https://user-images.githubusercontent.com/73315805/141355781-6b634fe0-be4c-4372-9942-0ddaa15ad1d4.png)

**Comment by INFINITY99K** [comment]
More bugs:
- Audio de-sync especially more noticeable when using the 60FPS mod.
- Frame-rate dips down to 45fps during Physics heavy scenes and when there's a ton of alpha particles on screen.
The game's multiplayer could be played through LDN and it plays fine though it suffers from the issues mentioned above.

**Comment by meisiek** [comment]
Since update 1.0.7168 Luigi's Mansion only woks with ResScale on native. With ResScale enabled the game flickers outside of its native resolution:

https://user-images.githubusercontent.com/24993330/149657511-8396e6a5-d077-4b7a-96fa-d7b3ffc8a0a9.mp4

1.0.7167 was the last version without this problem.
Windows 11, NVidia 3080 on latest official drivers (Version 511.23).

**Comment by mrjo118** [comment]
![luigi](https://user-images.githubusercontent.com/6963004/164552740-4fa358df-5053-4904-b7ea-8e4a26da0749.PNG)

Shadow issue still present and now sand doesn't render properly again on the latest build. Guessing it's to do with the shader cache rewrite

**Comment by mrjo118** [comment]
Might have been an issue with my existing shader cache being updated to the new version. I tried reloading the game after deleting the shader cache and PPTC cache and the sand rendered normally, aside from shadow being drawn all over it

**Comment by yell0wsuit** [comment]
Weird bug on Scream Park player icon:
![image](https://user-images.githubusercontent.com/5692900/166110369-10b4245a-3e37-4afd-8f26-0ff065abd15f.png)

**Comment by voldemort2826** [comment]
Graphical bug with player icon in ScreamPark menu:
![image](https://user-images.githubusercontent.com/102014910/166128875-a0dfd4b0-cd6a-4ae6-b0a2-91b45d34852a.png)

**Comment by Cheezballjones** [comment]
Game Update Version : 1.4.0
Current on Master: 1.1.335 (with Vulkan/OpenGL)

Hardware Specs :
CPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
GPU: NVIDIA RTX 2070 (522.25)
RAM: 16GB

*Ryujinx default settings used*

So far, I've not seen any improvements in performance in this game. Without the 60FPS/Dynamic Resolution Mods, the game's performance is less than 30FPS constantly. There was no difference in backends on my playthrough and I can also confirm that the previously noted graphical issues remain in the ScreamPark menu. The player count has these black boxes instead of simply just lighting up when the amount of players is chosen.

**Comment by purtealex** [comment]
Game Version : 1.0.0
Current on master : 1.1.398

Hardware
Ryzen 5 5600x
Amd RX 6700
16GB DDR4

The game crash with a AMD driver timeout when in 15 floor and in 10 floor when i go right on the picture.
It may be a tessellation problem, in the two case there is sand. There is also little shadow problem near the elevator

![ryujinx_capture_2022-11-28_17-31-21](https://user-images.githubusercontent.com/119345010/204604349-54acbb0c-ccec-4717-9b93-d13db9aee7e2.png)

**Comment by Kyle-Leu** [comment]
I noticed that the motion controls doesn't work when I use the vacuum cleaner to suck the ghosts.I'm sure I open the motion controls in the options because the motion controls work very well for Super Mario Odyssey in Ryujinx.

Using the Sony dualsense 5 controller to play Luigi's Mansion 3 in Ryujinx ，whether or not you use sdl direct connection or cemuhook with DS4Windows ,we can encounter the issue .

Environment
Ryujinx version: 1.1.515
Game version: Luigi's Mansion 3 V1.4.0
System Specs:
OS: Windows11
CPU: I7-10750H
GPU: RTX2060
RAM: 16G
Applied Mods :120FPS

**Comment by DeathWrench** [comment]
Shadow trailing effect:
![image](https://user-images.githubusercontent.com/45341450/215498593-8c1933b9-ef9e-4623-8cba-c6aa7449a67e.png)
Oldest build does not have this problem: 
![image](https://user-images.githubusercontent.com/45341450/215501941-c0447120-e977-4eac-be78-c4a807ffd732.png)

**Comment by apple020997** [comment]
I started playing the game about a month ago, and it's since then that I have some non-game-breaking issues. 
First, my hardware/software: 
Ryzen 7 5800X3D
16GB DDR4 3600
RX Vega 64 (watercooled in a custom loop) with the latest drivers (currently 23.3.1)
DualShock 4 connected via Bluetooth but without DS4Windows (I only use it for Ryujinx)
Win11 without any security feature enabled
Latest Ryujinx, updated daily (currently 1.1.665)
Luigi's Mansion 3 1.4.0 w/60FPS mod

Issues:
-There's some shadow trailing here and there, nothing major though
-I can't reach 60fps (with the mod) and can't maintain 30 without, it's around 52-53 and 26-28.
-Gyro aim/vacuuming doesn't work, neither via BT nor via USB (but works perfeclty in Super Mario Odyssey).

All in all it's a vastly superior experience vs. a real Switch, I'm happy anyways.

**Comment by Arnauw** [comment]
Upscaling is little bit broken using Vulkan, it looks kinda blurry and/or pixelated.
Someone on discord was able to reproduce the issue.

Here is the graphic options I was using, tried changing it a bit with no differences :
![image](https://user-images.githubusercontent.com/61736119/233323678-d36c1a8a-7152-4028-8f8b-ba5655b3f7fa.png)

Fullscreen screnshots
Vulkan :
![LM-ryujinx-x3-vulkan](https://user-images.githubusercontent.com/61736119/233323915-295542de-7c8e-4ee3-857e-d6c974ff7c92.png)

Opengl :
![LM-ryujinx-x3-opengl](https://user-images.githubusercontent.com/61736119/233323983-97a95e3b-5cad-46b4-9f4e-672f2d3e721c.png)

The issue is more noticable when you zoom in a little.
Vulkan :
![LM-ryujinx-x3-vulkan-zoom](https://user-images.githubusercontent.com/61736119/233324425-9fd549f0-b705-4fd9-8ce4-36ce1236d17f.png)

Opengl :
![LM-ryujinx-x3-opengl-zoom](https://user-images.githubusercontent.com/61736119/233324452-00aaeead-872d-4841-b10b-9714bd5ae0ec.png)

**Comment by amurgshere** [comment]
This game still crashes for me at the start of the game, just after you walk into the bathroom for the first time. Screenshots showing screens just before crash.

I turned on logging (except the debug logs) and attempted to find them upload them:

[Ryujinx-2023-05-02-213714.ips.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11372666/Ryujinx-2023-05-02-213714.ips.zip)

Environment
Ryujinx version: Latest Code Line as of 02/05/2023 (Built on M1)
Game version: Luigi's Mansion 3 V1.4.0
System Specs: M1 MacBook Air
Firmware: 15.0.1
OS: MacOS Ventura 13.3.1
CPU: M1
GPU: 8-Core M1
RAM: 16G
Applied Mods : None

<img width="1440" alt="Screenshot 2023-05-02 at 9 35 59 pm" src="https://user-images.githubusercontent.com/21148656/235655729-7f781770-75e9-41b9-9536-155e1ba74d53.png">
<img width="1440" alt="Screenshot 2023-05-02 at 9 37 08 pm" src="https://user-images.githubusercontent.com/21148656/235655777-81804f1d-673c-47b0-a459-0f4c445a1673.png">

Thank You

**Comment by Meistache** [comment]
@amurgshere  For me it's working perfectly fine on version 1.4.0 on Windows, I wonder if you have a bad dump or if there's any specific issue on Apple hardware (mine is too old to test so I hope anyone can help with that). Also it's possible that you can't play it with updates on your firmware version, try updating firmware to 16.0.2 or playing the base v0 instead.

Also I didn't notice any upscaling issues on Vulkan anymore since Ryujinx v1.1.739 or so, I might take some screenshots for evidences next time I play it.

**Comment by mrtnptrs** [comment]
Game version: 1.4.0
Ryujinx version: 1.1.819
Mods: Disable Dynamic Resolution.

Windows: 11 22H2
CPU: i7 13700KF
GPU: Nvidia RTX 4090
RAM: 64 GB DDR5
GPU-driver: 531.79
Renderer: Vulkan

Game runs relatively fine. Game seems to be always running at around 26-28 FPS instead of the game's default 30. This even happens when running at native resolution, having handheld mode activated and the Disable Dynamic Resolution mod installed, but also occurs thus without these. The game suffers from the trailing shadows issue still and moving objects seem to get a bit unusually pixelated/aliased as noted previously by others. Only in the introduction area, will report more info through edits if I find them.

![Ryujinx 1 1 819 - Luigi's Mansion 3 v1 4 0 (0100DCA0064A6000) (64-bit) 23_05_2023 21_29_11](https://github.com/Ryujinx/Ryujinx-Games-List/assets/4948213/153516df-e680-49a3-9198-ef5abe755518)
![Ryujinx 1 1 819 - Luigi's Mansion 3 v1 4 0 (0100DCA0064A6000) (64-bit) 23_05_2023 21_38_07](https://github.com/Ryujinx/Ryujinx-Games-List/assets/4948213/ef2e013b-3eca-4fd9-a891-c7f5df26504b)

Log file (99% stubbing spam):
[Ryujinx_1.1.819_2023-05-23_20-18-48.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11547844/Ryujinx_1.1.819_2023-05-23_20-18-48.zip)

**Comment by doyenho** [comment]
Game Version : 1.4.0 with multiple player pack 1 and 2
Current on master : 1.1.907

Hardware
Ryzen 5700U with radeon graphics
16GB

The game crash with a AMD build-in GPU in 10 floor when i go out of elevator and turn left.
Vulkan or OpenGL crash too.
The same as [purtealex] report before.

**Comment by OperatorEzekial** [comment]
![Screenshot 2023-06-28 015428](https://github.com/Ryujinx/Ryujinx-Games-List/assets/138070423/43f15840-8b97-4d04-b0bc-128ae51f71f2)



Game Version : 1.4.0 with multiplayer pack 1 and 2
Current on master : 1.1.941

Hardware
Ryzen 5700g
 with radeon graphics
16GB

Weird glitchy lines and grainy texture, i've tried different builds and same results.

**Comment by amurgshere** [comment]
I have retested my crash issue after entering the Bathroom from above and it no longer occurs with build of latest on MAC OS as of 17/08/2023.

Thanks for all your work on this guys, this emulator really is phenomenal!

**Comment by rudachmes** [comment]
Hardware:
Intel i3-13100F
AMD RX5500
8GB RAM

Even with build 1.1.999 the shadow(trailing) is still present.

**Comment by doyenho** [comment]
AMD Ryzen 5700U
16G RAM
Luigi's mansion crash when loading game
Ryujinx 1.1.1004
[Ryujinx_1.1.1004_2023-09-02_13-22-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12503243/Ryujinx_1.1.1004_2023-09-02_13-22-29.log)
[Ryujinx_1.1.1004_2023-09-02_13-25-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12503244/Ryujinx_1.1.1004_2023-09-02_13-25-00.log)

**Comment by Metal-Snake** [comment]
Game Version 1.2.1 and 1.4.0
Ryujinx version 1.1.1059
macOS 13.5.2
MacStudio M1 Max

Crashes on first start, the loading screen with the running dog is visible for a few seconds, then Ryujinx crashes.

[Ryujinx_1.1.1059_2023-10-22_00-16-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13061939/Ryujinx_1.1.1059_2023-10-22_00-16-34.log)

**Comment by gdkchan** [comment]
> Game Version 1.2.1 and 1.4.0 Ryujinx version 1.1.1059 macOS 13.5.2 MacStudio M1 Max
> 
> Crashes on first start, the loading screen with the running dog is visible for a few seconds, then Ryujinx crashes.
> 
> [Ryujinx_1.1.1059_2023-10-22_00-16-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13061939/Ryujinx_1.1.1059_2023-10-22_00-16-34.log)

Issue should be fixed on version 1.1.1060 or newer, can you test it again?

**Comment by Metal-Snake** [comment]
@gdkchan Game Version 1.4.0 works good now! Thank you.

Not sure if you guys care about older game versions too. So just in case:
Game Version 1.2.1 now crashes even earlier but only if there is no shader cache. 
It works fine if I first start 1.4.0. 
After purging shader cache it crashes again.

[Ryujinx_1.1.1061_2023-10-23_09-04-07.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13067085/Ryujinx_1.1.1061_2023-10-23_09-04-07.log)

**Comment by rudachmed** [comment]
1.1.1068 Shadow trail in Luigi's Mansion 3 is FIXED!, thanks

Specs:
Intel i3-13100F
AMD RX5500 (Vulkan, FSR)
8GB (4x2) RAM

Other PC:
AMD Ryzen 5 5600
AMD Vega 7 IGP (Vulkan, FSR)
16GB (8x2) RAM

**Comment by Vaskiemaia** [comment]
Shadows are still semi broken on Luigi's Mansion 3 when using 2x resolution scaling.

Not in the same way they were in the past, there are "line scans" across the floor instead.

Ryujinx:

Version: v1.1.10.69
Graphical Backend: Vulkan

Specs:

CPU: Ryzen 7800x3D
GPU: RTX 3080
RAM: 32GB 6000 Mhz DDR5

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/80223024/d090d7ef-715c-471b-af99-49260a4272eb)

**Comment by Ivan951236** [comment]
Game Update Version : 1.0.0

Current on master : 1.1.1083

 1. When a slight lag spike (i guess) appears during cutscenes, cutscene's audio may be mismatched for i guess like 3 to 5 seconds (Nvidia GeForce GTX 800 and below bug but bug may happend not because of your GPU) (Video Cutscene and some non-video cutscene thing)
 2. The note 1 may also apply to chase scene (and other non video cutscenes) in near begining

Hardware Specs :

CPU: Intel Core I3-2100

GPU: NVIDIA GeForce GTX 760

RAM: 8GB

Screenshots :
![MeowUwU](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/624462a0-8c87-4703-83ce-2afa90fea1b6)
![MeowUwU2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/971d2fc4-df46-4076-aa95-3820acd92b8a)
![MeowUwU3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/5e854f2a-10d5-4797-8ec0-8ece966c84aa)
![MeowUwU4](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/652105db-ba4e-4d16-8dbb-f496d5ac0d94)
![MeowUwU5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/08fa7cd9-d973-4214-9cff-531c7a69eeab)
![MeowUwU6](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/468bfe96-8670-43e2-9ae3-78b76440d1ee)

**Comment by Procket12** [comment]
Ryujinx Version: 1.1.1087
Game Version: 1.4.0
Operating System: Microsoft Windows 10.0.19045 (X64)
CPU: 12th Gen Intel(R) Core(TM) i9-12900K ; 24 logical
RAM: Total 47.7 GiB ; Available 32.6 GiB
Graphical Back End: OpenGL
GPU Driver:  23.11.1 (Current as of 11/15/2023)
![ryujinx_capture_2023-11-15_19-57-04](https://github.com/Ryujinx/Ryujinx-Games-List/assets/38678807/8c831285-b0f9-499e-a3e0-de1dc77c60fe)
![ryujinx_capture_2023-11-15_20-01-02](https://github.com/Ryujinx/Ryujinx-Games-List/assets/38678807/b0446f72-b18f-4b2b-a3a0-6384ed46c67b)

In the beach front room of the 11th Floor, your video drivers will crash if Luigi is left standing long enough or if you pull the cord that brings the ship to the dock, at which point the game will crash at the end of the cutscene. This renders the game completely unplayable beyond this point. Plus the sand also has the same graphical glitching as on the 10th floor. Also as on the 10th floor you can't even get in the room if you're using Vulkan instead of OpenGL. 

[Ryujinx_1.1.1083_2023-11-15_00-44-04.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13372133/Ryujinx_1.1.1083_2023-11-15_00-44-04.log)

[Ryujinx_1.1.1087_2023-11-15_19-55-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13372142/Ryujinx_1.1.1087_2023-11-15_19-55-40.log)

**Comment by Ivan951236** [comment]
Game Update Version : 1.4.0

Current on master : 1.1.1089

1. I updated my previous issue post with newer game version and of course a newer version of a emulator
2. Same effects from my previous issue post
3. Since the switch game i play the most often (I'm making Progress) is Luigi's Mansion 3, then a different screenshot is used

Hardware Specs :

CPU: Intel Core i3-2100

GPU: NVIDIA GeForce GTX 760

RAM: 8GB 1333Mhz DDR3


Screenshots :
![Meow1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/1af8bbfc-eb0b-4e65-a7bd-1824e13df742)
![Meow2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/19644212-af23-40bb-bc2c-68aab34910b1)
![Meow3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/d8bfff35-f68c-4302-89e2-87cc67c81c31)
![Meow4](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/4de23255-d0e0-4f6d-a28a-2d7bde784aa3)
![Meow5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/f7590e69-8be0-4f94-a069-1c3bd1ab04c5)
![Meow6](https://github.com/Ryujinx/Ryujinx-Games-List/assets/101629412/23fe49e5-303e-4344-8e0f-8f5adbdbeb59)

**Comment by rsouzadk** [comment]
Game Update Version : 1.4.0

Current on master : 1.1.1102

Game is playable. Just very low gpu usage and fps.

Hardware Specs :

CPU: Intel Core i5-13600k

GPU: NVIDIA GeForce RTX 3080

RAM: 32GB 6000Mhz DDR5

Screenshots :
![ryujinx_capture_2023-12-29_11-07-53](https://github.com/Ryujinx/Ryujinx-Games-List/assets/155170516/925df2f4-1c30-41c7-a9ac-70b951ed5c0c)
![ryujinx_capture_2023-12-29_11-08-28](https://github.com/Ryujinx/Ryujinx-Games-List/assets/155170516/f9b47a1c-ee3a-48d9-ab46-bafabc1663b9)

**Comment by rcv11x** [comment]
When using the native resolution I have noticed that the graphics look good, but when you activate the x2, x3 resolution both with FSR and without FSR... the shadows or textures are broken and look like with strange lines, attached screenshots of native vs x2 resolution.

Ryujinx:
- Version:  1.1.1140 (Ava)
- Backend: Vulkan

Hardware Specs:
-CPU: Ryzen 7 5800x3d
-GPU: RTX 3080
-RAM: 32GB 3200Mhz

Native:

![Ryujinx Ava_d3R1SrKlAC_native](https://github.com/Ryujinx/Ryujinx-Games-List/assets/38696644/58ddba3c-0ad2-4414-b417-792137804b9a)

Resolution x2:

![Ryujinx Ava_1RbXSeD3s4_x2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/38696644/4577dd63-2d22-478a-ba37-f4e5c1e31de7)

**Comment by visionrx7** [comment]
Game version: 1.4.0
Ryujinx version: 1.1.1191
Mods: Disable Dynamic Resolution, Disable Lens Flare, 60fps

OS: Batocera Linux ES V39cp
CPU: Ryzen 7 7735HS
GPU: Radeon 680m
RAM: 48GB DDR5
Renderer: Vulkan

As mentioned in a previous post by purtealex on Nov 29, 2022, I am getting a crash when using the Vulkan backend. The crash happens on the 10th floor if I try to walk past the picture on the wall. I can progress past the picture with OpenGL, but the game is nearly unplayable.

[Ryujinx_1.1.1191_2024-02-11_11-37-38.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14234038/Ryujinx_1.1.1191_2024-02-11_11-37-38.log)

![LM3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/83369397/d8a339c4-6124-472a-9b1c-db02f5a628ac)

**Comment by Tatobebop** [comment]
Game crashes on Floor 12F

I tried with the Vulkan drivers but the game crashes after the cinematic that shows the shark boss and the emulator closes.
[Vulkan Drivers Ryujinx_1.1.1202_2024-02-20_00-59-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14339512/Vulkan.Drivers.Ryujinx_1.1.1202_2024-02-20_00-59-23.log)
![VULKAN ryujinx_capture_2024-02-20_01-01-44](https://github.com/Ryujinx/Ryujinx-Games-List/assets/160565975/5ed77c45-d70f-4d73-998b-e3b634a7f0af)


With OpenGL drivers the image freezes on black as soon as the savegame loads in the dock but the sounds continue. You hear the boss presentation cinematic but once the action starts it hangs and then closes the emulator.
[OPEN GL Ryujinx_1.1.1202_2024-02-20_01-04-03.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14339510/OPEN.GL.Ryujinx_1.1.1202_2024-02-20_01-04-03.log)
![OPEN GL ryujinx_capture_2024-02-20_01-07-29](https://github.com/Ryujinx/Ryujinx-Games-List/assets/160565975/821ee306-c120-4366-99c2-074138a848b0)          

Ryujinx Version: 1.1.1202
Game Version: 1.4.0
Operating System: Windows 10  Home 22H2 19045.4046 (X64)
CPU: Intel(R) Core(TM) i7-5775C 
CPU @ 3.30GHz   3.30 GHz
RAM: Total 16 GiB 
Graphical Back End: Vulkan (RX6650XT)/OpenGL
GPU Driver:  31.0.21029.6002

**Comment by Tatobebop** [comment]
> Game crashes on Floor 12F
> 
> I tried with the Vulkan drivers but the game crashes after the cinematic that shows the shark boss and the emulator closes. [Vulkan Drivers Ryujinx_1.1.1202_2024-02-20_00-59-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14339512/Vulkan.Drivers.Ryujinx_1.1.1202_2024-02-20_00-59-23.log) ![VULKAN ryujinx_capture_2024-02-20_01-01-44](https://private-user-images.githubusercontent.com/160565975/306136697-5ed77c45-d70f-4d73-998b-e3b634a7f0af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzU5MTUsIm5iZiI6MTcxMzYzNTYxNSwicGF0aCI6Ii8xNjA1NjU5NzUvMzA2MTM2Njk3LTVlZDc3YzQ1LWQ3MGYtNGQ3My05OThiLWUzYjYzNGE3ZjBhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxNzUzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDI3OWEwN2YyZGQxMzJmZTE3MDg0YzlhOTQ1OTM1OGM5YzdkYzA4MzE3NDJjMmM5NDIyMWFjZjRjZWVkODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vgpXwQyso89NcDOfkM9HpZA_WDNAlN5gFYkDJSfQ950)
> 
> With OpenGL drivers the image freezes on black as soon as the savegame loads in the dock but the sounds continue. You hear the boss presentation cinematic but once the action starts it hangs and then closes the emulator. [OPEN GL Ryujinx_1.1.1202_2024-02-20_01-04-03.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14339510/OPEN.GL.Ryujinx_1.1.1202_2024-02-20_01-04-03.log) ![OPEN GL ryujinx_capture_2024-02-20_01-07-29](https://private-user-images.githubusercontent.com/160565975/306136189-821ee306-c120-4366-99c2-074138a848b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzU5MTUsIm5iZiI6MTcxMzYzNTYxNSwicGF0aCI6Ii8xNjA1NjU5NzUvMzA2MTM2MTg5LTgyMWVlMzA2LWMxMjAtNDM2Ni05OWMyLTA3NDEzOGE4NDhiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxNzUzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTg2NTM3NzgxMjU1ZWFkZTAyZGNiYTE1MTU5M2VmMWQ3MTZlM2U1NTQwODZlYWY5OTliNmM0ZDZiNTBhMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5c_Wg_tCF1ApAqhp6xJSc1ius56CIbwzpOJ9xHOY7PY)
> 
> Ryujinx Version: 1.1.1202 Game Version: 1.4.0 Operating System: Windows 10 Home 22H2 19045.4046 (X64) CPU: Intel(R) Core(TM) i7-5775C CPU @ 3.30GHz 3.30 GHz RAM: Total 16 GiB Graphical Back End: Vulkan (RX6650XT)/OpenGL GPU Driver: 31.0.21029.6002

FINALLY FIXED.

Game works on the same system with Wulkan drives  an Ryujinx 1.1.1287

**Comment by mj2k23** [comment]
> Very good compatibility up until trying to access floor 15. Once the floor starts loading, I get an AMD GPU driver crash and Ryujinx dies.
> 
> Ryujinx Version: 1.1.1330 Game Version: 1.4.0 Operating System: Windows 11 22H2 22621.3672 CPU: AMD Ryzen 9 5950X 16-Core Processor CPU @ 3.40GHz RAM: Total 32 GiB Graphical Back End: Vulkan (AMD Radeon RX 6750 XT) GPU Driver: 24.5.1 (31.0.24033.1003) Vulkan API: 1.3.277 Driver Version 23.40.33.01-240508a1-402593C-AMD-Software-Adrenalin-Edition
> 
> ```
> 00:01:43.876 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
> 00:01:44.877 |E| HLE.OsThread.4 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 13468 took more than 1000ms, resuming execution...
> 00:01:53.829 |E| GUI.RenderThread Gpu Create: Failed to create buffer with size 0x7FFF8 and type "HostMapped".
> 00:01:53.866 |E| GUI.RenderThread Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Ryujinx.Graphics.Vulkan.TextureView.SetData(ReadOnlySpan`1 data, Int32 layer, Int32 level, Int32 layers, Int32 levels, Boolean singleSlice, Nullable`1 region) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureView.cs:line 728
>    at Ryujinx.Graphics.Vulkan.TextureView.SetData(IMemoryOwner`1 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureView.cs:line 708
>    at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
>    at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 987
>    at System.Threading.Thread.StartCallback()
> ```

So I've been playing on Ryujinx, finally got to floor 15 and experiencing this crash now. On an M1 Pro MacBook. Game has been great till now, zero crashes. Any possible fix yet you're aware of? Would be extremely disappointed if I couldn't beat it after getting all the way to the end :(

**Comment by DemonicSavage** [comment]
@Unshackle8078 the lasers show up here just fine.

Vulkan, Arch Linux (Flatpak). AMD RX 7800 XT.

**Comment by P13rLu1** [comment]
I'm having problems with the audio.

Latest version of ryujinx, 60fps mod, no dynamic resolution mod, no lens flare mod.

Whenever i cutscene plays, the audio is delayed before it actually happens on the scree, i tried switching to opengl, switching audio driver. nothing

i'm dead in the water

**Comment by ekuland** [comment]
> Whenever i cutscene plays, the audio is delayed before it actually happens on the screen and it's really frustrating, i tried switching to opengl, switching audio driver. nothing

This happens when your cutscene is running slower than the expected speed and the audio stream runs away from it. This is quite common in video cutscenes if your CPU can't keep up.

**Comment by P13rLu1** [comment]
> This happens when your cutscene is running slower than the expected speed and the audio stream runs away from it. This is quite common in video cutscenes if your CPU can't keep up.

didn't happen on yuzu

**Comment by jucasleiva** [comment]
Ryujinx have plans to solve the áudio desync issue as yuzu had fixed the audio desync in one of the lasts update in games like astral chan,luigis mansion 3 and bayonneta 3

**Comment by P13rLu1** [comment]
> Ryujinx have plans to solve the áudio desync issue? As yuzu had fixed the audio desync in one of the lasts update in games like astral chan,luigis mansion 3 and bayonneta 3

Very nice, thank you for the support

**Comment by jucasleiva** [comment]
Does Ryujinx have plans to solve the áudio desync issue? As yuzu had fixed the audio desync in one of the lasts update in games like astral chan,luigis mansion 3 and bayonneta 3. I'm really enjoying Ryujinx and I would be very grateful if you could solve this as yuzu did

**Comment by furai** [comment]
In my experience switching to OpenAL fixes sound desync issues. But for me LM3 runs really choppy. No idea why.
