### ISSUE TITLE
Yu-Gi-Oh! Legacy of the Duelist: Link Evolution!

### ISSUE THREAD

**Issue by vagab0nd94** [Ryujinx/Ryujinx-Games-List#226]
## Game Name

Yu-Gi-Oh! Legacy of the Duelist: Link Evolution!

#### Current on `master` : 1.0.3592

Black screen with a weird error prompt and after 10-15 seconds ryujinx crashes.

#### Log file :

[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4131273/Ryujinx.log)
![20200129_221728 1](https://user-images.githubusercontent.com/60451939/73405465-41b42580-42f4-11ea-8b90-c21317f4949a.jpg)

**Comment by AcK77** [comment]
Needs an update because it was fixed in https://github.com/Ryujinx/Ryujinx/pull/911

**Comment by Seker-0** [comment]
## Update

#### Current on `master` : 1.0.3772

Missing texture only ingame
Some surfaces disappear

#### Status : Ingame 

#### Screenshots :
![bandicam 2020-02-24 19-54-32-352](https://user-images.githubusercontent.com/35269098/75155282-47115e00-5742-11ea-9bd5-bb4fa0616699.jpg)
![bandicam 2020-02-24 19-56-03-945](https://user-images.githubusercontent.com/35269098/75155302-555f7a00-5742-11ea-97cb-2c178b0d4dd6.jpg)
![bandicam 2020-02-24 19-59-21-706](https://user-images.githubusercontent.com/35269098/75155324-660ff000-5742-11ea-83d8-4fd3893e5b8d.jpg)

**Comment by AcK77** [comment]
Updated!

**Comment by EmulationFanatic** [comment]
## Yu-Gi-Oh! Legacy of the Duelist: Link Evolution!

#### Current on `master` : 1.0.4683

Game loads through menus and goes in-game, but there are still missing textures in menus and in the game, making it unplayable.

#### Screenshots :

![2020-06-08 10_29_34-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056354-5aec7300-a973-11ea-850c-6ee660dd6692.png)
![2020-06-08 10_29_50-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056357-5b850980-a973-11ea-9661-397afa01b207.png)
![2020-06-08 10_30_09-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056383-65a70800-a973-11ea-884f-ca3aaa5d6987.png)
![2020-06-08 10_30_12-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056397-693a8f00-a973-11ea-8373-7e0fb65df196.png)
![2020-06-08 10_30_22-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056414-6e97d980-a973-11ea-9f07-7268b7924c0e.png)
![2020-06-08 10_30_28-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056423-722b6080-a973-11ea-8f4f-a0035880df26.png)
![2020-06-08 10_31_31-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056433-748dba80-a973-11ea-8066-85aba2ef454d.png)
![2020-06-08 10_31_51-Ryujinx 1 0 4683 - Yu-Gi-Oh! Legacy of the Duelist _ Link Evolution v1 0 0 (0100](https://user-images.githubusercontent.com/62343878/84056453-79eb0500-a973-11ea-86ab-e5d8b815989f.png)


#### Log file :

[YLotDLE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4747291/YLotDLE.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Aquillion2** [comment]
![image](https://user-images.githubusercontent.com/80307355/130315883-f43ac438-2e17-48b4-8629-d12ec9148326.png)

Graphical corruption on cards still present in the latest version.

**Comment by JumpmanSr** [comment]
I don't know if it'll help, but at the time of writing (indcluding GDK's  commit above #2938 ^) this problem is not fixed.

Resolution and AF played small rolls for me, the higher the AF the better the shadows were which isn't so interesting. 
But, increasing the resolution made some cards go from not visible to visible, and going beyond 4x to as high of a resolution as possible, in my case 9x, yielded some very interesting results. 

Native Docked:
![native docked](https://user-images.githubusercontent.com/41526355/151137085-a45cb02b-2eee-4521-8a80-cec83991c34b.png)

4x Docked:
![4x res docked](https://user-images.githubusercontent.com/41526355/151137135-5d042464-9af2-45fb-86b9-9560c1e9bc0e.png)

9x Custom Docked:
![9x custom res docked](https://user-images.githubusercontent.com/41526355/151137160-7ba96972-3530-4c62-bfe3-d28564f9596b.png)

I can't really push past 9x without backscreens but its still producing high FPS at super high resolutions and is close to playable at this resolution so with the right fix this would be fully playable I'm guessing. 

Perhaps something is being sized incorrectly? I'm not really sure. Don't mind the "dirty" build number it's a clean branch from master build  1.1.9 (1/25/2022)

Also if it's any help I wanted to look at the OpenGL Error, one stuck to me in particular:
`GPU.MainThread Gpu UpdateVertexAttribState: Invalid attribute format 0x25E00000`

I hope this helps get this fixed :)

**Comment by Hinkiii** [comment]
![image](https://user-images.githubusercontent.com/1348768/153741658-f83ab601-ee1c-4b30-b073-7d12ea6f69b3.png)
9x oddly enough seems fine? I haven't done anything to test though

**Comment by Hinkiii** [comment]
You basically have to switch to native res when not in a match then switch to 9x after loading in it seems or else it'll just be invisible again

**Comment by Bl4ckSh4rk** [comment]
I can confirm this issue has recently been fixed by https://github.com/Ryujinx/Ryujinx/pull/3328
Ignore the FPS, game runs smoothly but doesn't like screenshots.
![ygo](https://user-images.githubusercontent.com/25778475/168262447-057eead5-cab1-4508-99c2-d53fc00dcf9e.png)

**Comment by GamerzHell9137** [comment]
OP should be updated with the latest info.
Game plays fine, runs fine. No graphical issues. Last post shows how the game looks now

**Comment by GamerzHell9137** [comment]
Reporting again, game runs fine on both backends and is emulated with no graphical issues with and without the upscaler.

![image](https://user-images.githubusercontent.com/2002038/182199970-38354efa-5eed-4b1c-8dd3-aa7e857721d4.png)

**Comment by GamerzHell9137** [comment]
## Yu-Gi-Oh! Legacy of the Duelist: Link Evolution!

#### Game Update Version : 1.0.0

#### Current on `master` : 1.1.208

#### Graphics Backend : Vulkan and OpenGL

Game runs fine on both backends and is emulated with no graphical issues with and without the upscaler.

#### Hardware Specs : 

##### CPU: Ryzen 3600
##### GPU: NVIDIA RTX 3060 Ti
##### RAM: 16 GB

#### Screenshots :

![image](https://user-images.githubusercontent.com/2002038/183297095-c2804226-3850-46d4-835f-1d76e299f1d9.png)
![image](https://user-images.githubusercontent.com/2002038/183297094-5137ac52-cd18-4920-9eef-d97dac2a0047.png)
![image](https://user-images.githubusercontent.com/2002038/183297097-df285c4f-8d29-49de-9a94-e25f7480cb44.png)

#### Logs:

[Ryujinx_1.1.208_2022-08-07_16-49-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9276997/Ryujinx_1.1.208_2022-08-07_16-49-23.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Aquillion2** [comment]
1.1.371 issue, only occurring on the Steam Deck:

On the Steam Deck, the videos for playing an "iconic card" (eg. Stardust Dragon) or when an opponent plays one (eg. in the first real Arc V story duel - not the tutorial one) sometimes don't play properly, displaying a pink screen instead.  Waiting does nothing, but the game is not crashed; you can open the game's start menu and quit the duel.  Also, for some reason every time I open the menu the video advances a tiny bit before the pink screen returns, so it is possible to brute force past this by opening and closing the menu repeatedly.

I have had this happen with both OpenGL and Vulkan, but it seems to happen at random (not every single time one of the videos play), so it is not easy to reproduce.  I've only encountered this on the Steam Deck, never on desktop.

**Comment by GamerzHell9137** [comment]
@Aquillion2 Can you record and post it?

**Comment by Aquillion2** [comment]
Harder to do on the Steam Deck than if it occurred on the desktop version,
but I will try and post it here if I manage!

**Comment by DMaster2** [comment]
The game keep crashing during battles (build 1.1.680, vulkan)

**Comment by GitHubDan01** [comment]
pink screen is still a problem i keep getting it

**Comment by pronightra** [comment]
I do not see this issue being posted for 
Ryujinx version 1.1.140

going to deck edit and going into any of the recipes or doing deck creation freezes the game. Problem also exist when searching for a card in card edit mode.
