### ISSUE TITLE
Fire Emblem: Three Houses

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx-Games-List#230]
#### Current on `master` : 1.0.3635

Audio gets jittery occasionally and goes back to smooth.
During going between other events the intro to it isn’t output, this may be because it may be a video and the emulator doesn’t decode video as of the latest master.

The audio of the game is messed up, especially during the beginning of the game where the background noise is ear rap at its finest, and when you try to mess with the audio 
in the Options>General tab of the game doesn’t exactly do what its suppose to. 
I turned down the SFX Volume completely and messed with the voice volume to be louder but then
I was nearly unable to hear the characters voices and the SFX volume was just horrendous. 
The 3d over world area seems to render very well have not seen issues with how its rendered other than occasionally you will see a textures pop out and back in for some reason
At the end of a characters paragraph of talk the last word of that sentence will stutter. 
Example (Jeralt-t)

Playing thru the more strategic part of the game the map has textures popping in and out depending where your screen is, the texture will either be there or it will not
The Fog is Rendered Very thick and incorrectly can’t see 5 inches from yourself in a building but magically clears up so you can see further outside but it’s still off because you can’t hardly see anything further back.

Sometimes the character pictures will get swapped for another characters picture.

#### Screenshots :

![Annotation 2020-02-04 194902](https://user-images.githubusercontent.com/45114656/73810614-e5d21c80-478b-11ea-83da-b7999aca4fb4.png)
![Annotation 2020-02-04 195015](https://user-images.githubusercontent.com/45114656/73810617-e8cd0d00-478b-11ea-9567-4948eac7e0d2.png)
![Annotation 2020-02-04 195146](https://user-images.githubusercontent.com/45114656/73810624-eb2f6700-478b-11ea-9790-4c6ad59aba7b.png)
![Annotation 2020-02-04 195206](https://user-images.githubusercontent.com/45114656/73810629-ecf92a80-478b-11ea-8ffe-5258d18adabe.png)
![Annotation 2020-02-04 200336](https://user-images.githubusercontent.com/45114656/73810633-eec2ee00-478b-11ea-8e39-c4a3a4b748e6.png)
![Annotation 2020-02-04 200414](https://user-images.githubusercontent.com/45114656/73810636-f08cb180-478b-11ea-9cef-c4f826ecffb8.png)
![Annotation 2020-02-04 200450](https://user-images.githubusercontent.com/45114656/73810638-f387a200-478b-11ea-9dfa-b64dba4c2797.png)
![Annotation 2020-02-04 200520](https://user-images.githubusercontent.com/45114656/73810645-f6829280-478b-11ea-8f19-72db1d87eae1.png)
![Annotation 2020-02-04 201816](https://user-images.githubusercontent.com/45114656/73810651-f97d8300-478b-11ea-9ace-05f1c4ba51b0.png)
![Annotation 2020-02-04 201849](https://user-images.githubusercontent.com/45114656/73810659-fc787380-478b-11ea-94c6-36bddb79b021.png)
![Annotation 2020-02-04 201925](https://user-images.githubusercontent.com/45114656/73810669-000bfa80-478c-11ea-904d-150c3aad2272.png)
![Fire Emblem Three Houses Stratigic Battle_Trim_Trim](https://user-images.githubusercontent.com/45114656/73811755-28e1bf00-478f-11ea-9da2-e51edb276d61.gif)

**Comment by zerorise** [comment]
build version: 1.0.5327, and some older 1.0.5 ish

All cuteness seem to be working fine. 

Every map i been on has been able to be completed.

Only real issue iv seen is the songstress class cant use sing, which makes it pointless, but its not required for the game so it dosent mater. 

Some times small audio stutter in during voiced lines usually goes away, but some times if it last long enough can crash game. 

Some artifact when viewing enemies range. 

Some log files.
[Ryujinx_2020-09-11_13-21-57.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5211450/Ryujinx_2020-09-11_13-21-57.log)
[Ryujinx_2020-09-11_12-52-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5211451/Ryujinx_2020-09-11_12-52-00.log)
[Ryujinx_2020-09-11_13-43-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5211452/Ryujinx_2020-09-11_13-43-15.log)

**Comment by crazyen** [comment]
I have encountered a similar crashing problem. Every time Dorothea (dancer class) uses the dance ability the screen freezes for a few seconds, the audio stutters a bit and then the game crashes.  It happened in 1.0.5391 and older versions.

In the log file there is "GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction".
[Ryujinx_2020-09-23_22-10-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5290666/Ryujinx_2020-09-23_22-10-35.log)

**Comment by crazyen** [comment]
> I have encountered a similar crashing problem. Every time Dorothea (dancer class) uses the dance ability the screen freezes for a few seconds, the audio stutters a bit and then the game crashes. It happened in 1.0.5391 and older versions.
> 
> In the log file there is "GUI.RenderLoop Gpu Log: Shader translator: Invalid instruction".
> [Ryujinx_2020-09-23_22-10-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5290666/Ryujinx_2020-09-23_22-10-35.log)

Dorothea (dancer class) can use the dance ability in Ryujinx version 1.0.5573. Thank you.

**Comment by njdom24** [comment]
I've encountered a graphical issue for a few months (as far as I know, it's always been present). There's a staircase-esque lighting issue in part of the monastery.

Images:
![handheld](https://user-images.githubusercontent.com/15348462/115441783-40179b80-a1df-11eb-9efc-16002b114f14.png)
![docked](https://user-images.githubusercontent.com/15348462/115441797-44dc4f80-a1df-11eb-91d7-1ec76da5bec0.png)

Resolution scaling does not change the issue, only switching between handheld/docked modes.
OS: Arch Linux
GPU: AMD Radeon RX 5700 XT (NAVI10, DRM 3.40.0, 5.11.14-147-tkg-bmq, LLVM 11.1.0)
Mesa 21.0.2-1

Game launched with `GDK_BACKEND=x11 glsl_zero_init=true radeonsi_clamp_div_by_zero=true mesa_glthread=true vblank_mode=0 MESA_EXTENSION_OVERRIDE="-GL_KHR_texture_compression_astc_ldr -GL_KHR_texture_compression_astc_sliced_3d"` environment variables.

**Comment by Ryu99990** [comment]
Is it completely playable now

**Comment by Zuyoart** [comment]
**Current on master : 1.0.6887**
**Game version: 1.2.0 (+all dlc)**

**Playability**
The game does not soft lock at all, fully playable. 

**Quirks**
Except on master the monastery walking is slow (Power PR should fix this).

**Recent improvements**
PR's made in the last 24 hours have fixed many visual problems somehow. Before the sky was messed up and the lightning was blander (not sure on the latter).

**Annoyances**
Still there is this one problem spot: when walking out of your personal quarters out by hitting explore run towards the flower place with the windmill. It will for a certain section spam creation and deletion of the same map over and over again. The frames drop and its a mess, works everytime.

Often enough, there is this thing where after a while the whole image judders up and down. Restart fixes it. It looks as if the image cant fit the screen or is looking to fit, except it did before.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by AMTZAk** [comment]
Mine is crashing on the prologue after I complete the first phase before that I completed the entire map but the game crashed on the sothis cutscene. I can play other games like Sword and Shield just fine only getting issue with this game

**Comment by Greenf1re** [comment]
Crashes on Razer Blade 15 Base 2021 (RTX 3070/i7-10750H)
Game works like normal for battle maps and menus but crashes immediately when trying to load the monastery. Tried it on different saves and it only crashes when loading the Monastery. 
[Ryujinx_1.0.6918_2021-06-23_12-18-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6704099/Ryujinx_1.0.6918_2021-06-23_12-18-44.log)

**Comment by sadgachawhalenoises** [comment]
Consistent crash on Marianne retaliating upon being attacked and casting what I believe to be nosferatu.
Have attempted fiddling with settings (vsync, ignore missing services, etc.), same result every time.
Log file of latest crash attached, can supply more data if requested.

[Ryujinx_1.0.6956_2021-07-08_14-55-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6784814/Ryujinx_1.0.6956_2021-07-08_14-55-10.log)

**Comment by garie234** [comment]
^same problem, played the mock battle early in the game and froze/crashes when any characters cast nosferatu spell

**Comment by gdkchan** [comment]
Attach a save file to allow the issue to be reproduced.

**Comment by garie234** [comment]
It seems like if I use a spell with heavy alpha effects like nosferatu or thunder the game freezes momentarily or just crash
running the game using Intel 9600k and RTX 2060 super at 2x resolution scale with AF set to auto
[save file.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6786851/save.file.zip)

**Comment by sadgachawhalenoises** [comment]
Save 1 manual save directly before fight
[save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6787039/save.zip)

**Comment by garie234** [comment]
Just updated the game to the latest version(1.0.6957) and the freezing/crashing when casting spell is fixed

**Comment by sadgachawhalenoises** [comment]
Upon updating to Ryujinx 1.0.6957 the game no longer crashes upon nosferatu in handheld native with vsync enabled.
Does crash in handheld native vsync disabled

Does crash in 2x upscaling docked vsync enabled

[Ryujinx_1.0.6957_2021-07-09_10-32-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6790008/Ryujinx_1.0.6957_2021-07-09_10-32-24.log)

Does crash in native docked vsync enabled
[Ryujinx_1.0.6957_2021-07-09_10-38-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6790026/Ryujinx_1.0.6957_2021-07-09_10-38-14.log)

Does not crash in native docked vsync enabled with "Expand DRAM size to 6GB" hack enabled
Does not crash in docked 2x vsync enabled with "Expand DRAM size to 6GB" hack enabled

**Comment by Noirgheos** [comment]
Some shades of blue such as Seteth's coat and Shamir's hair appear to have some kind of color artifacting issues going on.

i7 8700K
GTX 1080 Ti
Windows 10 LTSC 1809

![Screenshot (824)](https://user-images.githubusercontent.com/35716495/128209188-1aa21bd9-891d-43f6-b5b7-ef92954c8b7f.png)

Same issue with 1x scaling.

**Comment by Noirgheos** [comment]
Sword of the Creator has this graphical bug on Chapter 5. 

![Screenshot (826)](https://user-images.githubusercontent.com/35716495/128380650-611177ef-a9f5-4eff-83ff-33156796ac39.png)

**Comment by LuckyLuigiX4** [comment]
Game keeps crashing when using Thunder During the Mock Fight early in the game. More specifically the display freezes while the audio keeps going, but then it uses an unnecessary amount of RAM and CPU causing everything on my computer to freeze until Ryujinx crashes or I kill the program before it happens. 
GPU: NVIDIA GeForce GTX 1050 Ti
CPU: AMD Ryzen 5 1600 (12) @ 3.2GHz
Log File:

[Ryujinx_1.0.7108_2021-11-27_16-14-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7612419/Ryujinx_1.0.7108_2021-11-27_16-14-23.log)

Reading above I thought this issue was fixed in the past, but I guess not?

**Comment by LuckyLuigiX4** [comment]
Game keeps crashing when using Thunder During the Mock Fight early in the game. More specifically the display freezes while the audio keeps going, but then it uses an unnecessary amount of RAM and CPU causing everything on my computer to freeze until Ryujinx crashes or I kill the program before it happens. 
GPU: NVIDIA GeForce GTX 1050 Ti
CPU: AMD Ryzen 5 1600 (12) @ 3.2GHz
Log File:

[Ryujinx_1.0.7108_2021-11-27_16-14-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7612419/Ryujinx_1.0.7108_2021-11-27_16-14-23.log)

Reading above I thought this issue was fixed in the past, but I guess not?

**Comment by Raishinot** [comment]
## Game Name

#### Game Update Version : 1.2.0

#### Current on `master` : 1.0.7115

Likely same issue as above and the ones mentioned around july?
Game freezes indefinitely upon using Nosferatu (potentially other things?). Audio continues in the background, cant stop simulation or close the emulator afterwards without going into taskmanager. No response to controls while frozen (e.g listening to sound if it is still running). 

Tested with, crashes on all of them: 
60 FPS mod On/Off
6GB Feature On/Off
VSync On/Off
Docked/Handheld.

```
Last error returned:
00:02:16.343 |W| HLE.OsThread.9 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
```

#### Hardware Specs : 

##### CPU: Ryzen 2600x
##### GPU: Zotac 2060S
##### RAM: 16GB


#### Log file :

[Ryujinx_1.0.7115_2021-12-05_10-47-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7655618/Ryujinx_1.0.7115_2021-12-05_10-47-24.log)

Save File if needed for testing:
[slot00.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7655647/slot00.zip)

**Comment by lagunaxii** [comment]
> 

same Issuse like you T_T

**Comment by lagunaxii** [comment]
Found a fix, updated Nvidia driver. Went into Nvidia control panel under Manage 3D Settings. Went into Program Settings Customized the Ryujinx Nvidia Profile. Turned on Vertical sync and put Low Latency Mode on Ultra. (It still freezes on the first use of thunder, **but you just need to wait a few minutes, and it won't freeze on any subsequent uses)**
Source: Reddit
I Tested, it work :D

**Comment by kamikazilucas** [comment]
on chapter 4 i use the fire attack and the game freezes with the video i can control stuff but i cant see anything

**Comment by lagunaxii** [comment]
while the game freezes, do not press anything and wait for a few minutes the problem will be over. ( I have the same your problem with thunder & fire magic)

**Comment by leaflux** [comment]
I came across 2 similar issues with spells.

When a character casts Nosferatu, the game locks up for several minutes, but it eventually recovers on its own like lagunaxii described above.

From then on, the Nosferatu animation data seems to be saved to my Shader Cache. The next time I try to start the game after having seen the Nosferatu animation, it crashes before the game even starts, during the time the Shader Cache for Three Houses is being loaded in by Ryujinx. Deleting my Shader Cache also stops the game from crashing in this circumstance.

Here's my save data for testing.

[0000000000000008.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7964976/0000000000000008.zip)

**Comment by cheungyau2022** [comment]
The fps drops to as low as 2-5 when walking around outside my room. But during battle I can easily get 60 fps. Good thing is the game never crashes on my PC so I can still play through.
Specs of my PC:
Intel i3 8100
AMD RX 460 4gb
16gb ram
Ubuntu 20.04

**Comment by falconzzz00** [comment]
where can I get the 1.0.6906 version?

**Comment by MetrosexualGarbodor** [comment]
@falconzzz00 what do you want that version for, just use the latest

**Comment by falconzzz00** [comment]
> @falconzzz00 what do you want that version for, just use the latest

my game crash on the latest (1.1.213)

**Comment by MetrosexualGarbodor** [comment]
Come to [Discord](https://discord.gg/ryujinx) for help, the game works fine on the latest version.

**Comment by Bjorn29512** [comment]
**DESCRIPTION:** 

Pink Artifacts on hair of NPCs and Clothing items of others. (Unaffected by scaling) (Vulkan API)

**SPECS:** 
    12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.82 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3
    Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0
    GPU: 'NVIDIA GeForce GTX 1660 SUPER' running on driver 526.47.0.0
    
**MEDIA FILES SHOWCASING THE ISSUE :**

![image](https://user-images.githubusercontent.com/110204265/199127611-b5613aac-0c89-4629-929a-851b42c6a6db.png)

**REPRODUCTION STEPS AND SAVE FILE :**
- Load file 17 in the save menu the guy should be right in front, walk towards him and the issue should appear.
[FE3H save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/9905587/FE3H.save.zip)

**LOG FILE :**
[Ryujinx_1.1.335_2022-11-01_04-41-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9905588/Ryujinx_1.1.335_2022-11-01_04-41-43.log)

**ADDITIONAL COMMENTS :**
Could be related to FP 16 precision but i am not sure better for someone more experienced to do testing on their own.

**Comment by Janarab** [comment]
I'm consistently crashing when enemies cast fire on me in chapter 6

I've had issues with prolonged freezes and stuttering with other spells but no crashes before this, even from other enemies using fire on me.

Specs:
AMD Ryzen 7 5800X3D 8-core
32 GB RAM
AMD Radeon RX 6700 XT
Windows 11

Save file:
[FE3H Chapter 6 mission.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/10083495/FE3H.Chapter.6.mission.zip)

Log file:
[FE3H Chapter 6 crash log.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/10083498/FE3H.Chapter.6.crash.log.txt)

**Comment by Digitaln3ko** [comment]
> **DESCRIPTION:**
> 
> Pink Artifacts on hair of NPCs and Clothing items of others. (Unaffected by scaling) (Vulkan API)
> 
> **SPECS:** 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.82 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3 Operating system: Windows, Major: 10, Minor: 0, Build: 22000, Service Pack: none, Compatibility mode: 0 GPU: 'NVIDIA GeForce GTX 1660 SUPER' running on driver 526.47.0.0
> 
> **MEDIA FILES SHOWCASING THE ISSUE :**
> 
> ![image](https://user-images.githubusercontent.com/110204265/199127611-b5613aac-0c89-4629-929a-851b42c6a6db.png)
> 
> **REPRODUCTION STEPS AND SAVE FILE :**
> 
> * Load file 17 in the save menu the guy should be right in front, walk towards him and the issue should appear.
>   [FE3H save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/9905587/FE3H.save.zip)
> 
> **LOG FILE :** [Ryujinx_1.1.335_2022-11-01_04-41-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9905588/Ryujinx_1.1.335_2022-11-01_04-41-43.log)
> 
> **ADDITIONAL COMMENTS :** Could be related to FP 16 precision but i am not sure better for someone more experienced to do testing on their own.

It is related to fp16, this looks exactly like what would happen if you run fp32 to emulate fp16. Maybe gtx 1660 is tagged to run fp32 instead on Ryujinx for performance reasons? fp16 performance on a 1660 is about half that of fp32.

**Comment by chefe23** [comment]
Only characters' textures work. Everything was perfect before. Started looking like this after a cutscene.

![image](https://user-images.githubusercontent.com/122596305/212265086-0816aef6-cdee-4303-bddc-4b50631210a4.png)
![image](https://user-images.githubusercontent.com/122596305/212265101-9a02ea23-32e5-4d50-8710-2c77a3063cd4.png)

Specs: AMD Ryzen 5 5600H with Radeon Graphics | 12 Threads | 13.86 GiB RAM | TSC: 3.294GHz | AVX+ | FMA3 Operating system: Windows, Major: 10, Minor: 0, Build: 22621, Service Pack: none, Compatibility mode: 0
GPU: 'NVIDIA GeForce GTX 1650' running on driver 528.2.0.0

Log File: 
[Ryujinx_1.1.551_2023-01-13_04-40-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10409274/Ryujinx_1.1.551_2023-01-13_04-40-19.log)

**Comment by ThisNekoGuy** [comment]
## Description:
The game has poor speed, it causes the audio and visuals to be out of sync.
For comparison, this is not the case with Yuzu, and I honestly can't convince myself to play the game with Ryujinx in this state.

## Reproduction Steps:

1. Install the 1.2.0 update and the game's 6 DLCs
2. Run the game (I ran the game via .NSP file)
3. Wait at the title screen without touching anything
4. The title screen video will play, which will seem to run fine, however...
5. Wait a bit longer after that at the title screen, and the game will do a character showcase that will demonstrate the speed of the game.

## System Information:
OS: Arch Linux
CPU: AMD Ryzen 7 3700X (16) @ 4.05GHz
RAM: 32 GBs @ 3200 MHz
GPU: RTX 2080 Ti
GPU Driver:  535.43.02 (Open-GPU Kernel Module)
Switch Firmware Version: 16.0.3
**Log:** [_Ryujinx_1.1.884_2023-06-11_15-01-45.log_](https://github.com/Ryujinx/Ryujinx-Games-List/files/11715628/Ryujinx_1.1.884_2023-06-11_15-01-45.log)

**Comment by Gragan1** [comment]
Game runs well, 1.2.0 Update and all DLCs however after recruiting Anna when in battle her sprite is missing and if she attacks or is attacked i get CTD 

CPU: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz   2.30 GHz
RAM: 64 G
GPU: Nvidia Geforce RTX 2070
Switch Firmware:  16.0.3
Ryujinx V: 1.1.970

**Comment by jgvinholi** [comment]
Hello. It always crashes when casting a special spell with LT button. I have tried everything, every configuration possible, but nothing works. 

Mac Mini M2
16GB
Version 1.1.999 

[Ryujinx_1.1.999_2023-08-20_16-25-04.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12389154/Ryujinx_1.1.999_2023-08-20_16-25-04.log)

**Comment by hakcumx** [comment]
Using 'Divine Pulse' ability cause 100% crash on MacOS Sonoma(14.0) M1 Max 64GB.
Including ryujinx version 1.1.1036~1.1.1047.
When crash happend no ryujinx logs were dumped, only got MacOS error log.

`Thread 60 Crashed:
0   libsystem_kernel.dylib        	       0x1843cb11c __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x184402cc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x184312a50 abort + 180
3   Ryujinx                       	       0x103500000 PROCAbort + 64
4   Ryujinx                       	       0x1034fff10 PROCEndProcess(void*, unsigned int, int) + 388
5   Ryujinx                       	       0x103143d94 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 876
6   Ryujinx                       	       0x103143e78 DispatchManagedException(PAL_SEH
[crash_log.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/12837566/crash_log.txt)
Exception&, bool) + 68
7   Ryujinx                       	       0x1030a6e9c IL_Throw(Object*) + 536
8   ???                           	       0x10b5fa914 ???
9   ???                           	       0x10c5ca518 ???
10  ???                           	       0x10c5c9148 ???
11  ???                           	       0x10c804a78 ???
12  ???                           	       0x10c804888 ???
13  ???                           	       0x10c5759b8 ???
14  ???                           	       0x10b434180 ???
15  ???                           	       0x10ab24030 ???
16  ???                           	       0x1074bc4bc ???
17  ???                           	       0x1074bc3a8 ???
18  ???                           	       0x1074bc1a0 ???
19  Ryujinx                       	       0x1031cdff4 CallDescrWorkerInternal + 132
20  Ryujinx                       	       0x1030438a0 DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 272
21  Ryujinx                       	       0x103057fbc ThreadNative::KickOffThread_Worker(void*) + 148
22  Ryujinx                       	       0x103011cdc ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) + 260
23  Ryujinx                       	       0x103012248 ManagedThreadBase::KickOff(void (*)(void*), void*) + 32
24  Ryujinx                       	       0x103058094 ThreadNative::KickOffThread(void*) + 172
25  Ryujinx                       	       0x1035045ec CorUnix::CPalThread::ThreadEntry(void*) + 380
26  libsystem_pthread.dylib       	       0x184403034 _pthread_start + 136
27  libsystem_pthread.dylib       	       0x1843fde3c thread_start + 8
`

**Comment by SomaBenjamin** [comment]
> It is related to fp16, this looks exactly like what would happen if you run fp32 to emulate fp16. Maybe gtx 1660 is tagged to run fp32 instead on Ryujinx for performance reasons, though that doesn't make sense as fp16 performance on a 1660 is about 2:1 to fp32 A fix would be and I'm assuming you aren't forcing your card to run fp32, for them to allow the fp16 set to be used for that card, which should be a huge performance uptick in that game.

I have a Nvidia RTX 3050, and I'm running into the same problem. How do I force fp16 instead of fp32?

**Comment by StarShardDragon** [comment]
one of the DLC for the game cannot be used on Ryujinx it cause the game to close the emulator when  you have it enable and try to open the game. the dlc is the one with the side story  at the very least it is doing that on my side

**Comment by antoniodesousa** [comment]
> one of the DLC for the game cannot be used on Ryujinx it cause the game to close the emulator when you have it enable and try to open the game. the dlc is the one with the side story at the very least it is doing that on my side

It works fine for me.
[Ryujinx_1.1.1330_2024-06-12_13-18-02.log.zip](https://github.com/user-attachments/files/15803906/Ryujinx_1.1.1330_2024-06-12_13-18-02.log.zip)

CPU: Ryzen 9 6900HX
GPU: AMD RX 6600
RAM: 64 GB DDR5
OS: Windows 11 Pro 23H2

**Comment by Hoe2020** [comment]
On Mac the audio seems to lag 10 seconds behind the visuals.

**Comment by SpicyWolf57** [comment]
On Mac M3, Ryujinx versions past 1.1352 have a graphical bug that appears as flickering black square/circles/boxes. 

This is on version 1.1351
![image](https://github.com/user-attachments/assets/942024b3-d028-4ea6-a433-53aac3a035e3)

And this is on version 1.1352
![image](https://github.com/user-attachments/assets/32d49759-e820-428a-96d3-1f9876ddb687)

I don't know what causes the issue, but according to the changelog it was because of a change to the guest barrier something or other.

**Comment by muchhesitate** [comment]
I'm seeing graphical glitches where blue squares are visible around characters. This happens when exploring in the monastery, and from what I can tell only in indoor scenes (like the dining hall).

Specs:
* Game version 1.2.0, no mods
* Ryujinx 1.1.1385 on Linux (flatpak version)
* AMD Ryzen 7840U with Radeon 780M iGPU
* Vulkan renderer, default resolution scale

Just started playing this game, so I can't say whether this was introduced recently.

![2024-09-09T11:31:04,986983925+02:00](https://github.com/user-attachments/assets/daca737b-c063-4c7a-9a3b-d91e9cff3ea5)

**Comment by which-guy** [comment]
I'm seeing the blobs around characters as well. Both Mac and Linux. It starts with v1352.

It's easiest to see in the dining hall, other shadowy areas.

I have a save file which you can load and see a cutscene which showcases the issue. If anyone would like that then let me know.

<img width="1427" alt="Screenshot 2024-09-01 at 3 06 02 PM" src="https://github.com/user-attachments/assets/909aa6e8-6df0-44cb-a41d-df035b2972eb">
