### ISSUE TITLE
Pikmin 3 Deluxe

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2822]
#### Current on `master` : 1.0.5598

Game loads and plays smoothly, after a small amount of initial stutter.

#### Screenshots :

![2020-11-02 07_17_15-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878267-a5340f00-1cdb-11eb-91e5-e279efa7391d.png)
![2020-11-02 07_07_59-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878289-ad8c4a00-1cdb-11eb-843f-ba636dcf76de.png)
![2020-11-02 07_08_14-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878316-ba10a280-1cdb-11eb-89dc-ac8e960d791d.png)
![2020-11-02 07_09_03-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878323-bd0b9300-1cdb-11eb-8781-cf2844f407aa.png)
![2020-11-02 07_09_06-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878330-bf6ded00-1cdb-11eb-9122-68936a24410d.png)
![2020-11-02 07_10_02-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878365-c7c62800-1cdb-11eb-8e26-6956eb0a4b69.png)
![2020-11-02 07_10_20-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878392-d14f9000-1cdb-11eb-8e7e-fda5470b3fc4.png)
![2020-11-02 07_11_59-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878419-dad8f800-1cdb-11eb-82be-54a7f7f1ecb7.png)
![2020-11-02 07_12_42-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878438-e1676f80-1cdb-11eb-9988-0424a3ddc5ba.png)
![2020-11-02 07_14_06-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878449-e9271400-1cdb-11eb-8bb9-a8294a57570c.png)
![2020-11-02 07_14_11-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878454-ec220480-1cdb-11eb-805d-eb604460ec59.png)
![2020-11-02 07_15_37-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878469-f17f4f00-1cdb-11eb-9898-a35caaa0dc7e.png)
![2020-11-02 07_16_43-Ryujinx 1 0 5598 - Pikmin 3 Deluxe v1 0 0 (0100F4C009322000) (32-bit)](https://user-images.githubusercontent.com/62343878/97878513-fb08b700-1cdb-11eb-93c0-d19eb645a009.png)

#### Log file :

[P3D.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5475609/P3D.zip)

**Comment by Zuyoart** [comment]
**Game Update Version : 1.1.0
Current on master : 1.0.6883**

Eventhough its 'playable', perhaps even enjoyable, there are currently some bugs (maybe not implemented) that are degrading the experience quite a bit.

**Holographs and all sorts of light or translucent things**

- Data files (yellow holographs) scattered throughout the game are invisible but the light they emit can be seen on the ground. This makes it so you get a popup-infographic with sometimes useless tutorial while exploring or fighting. Also potentially makes it harder for beginners to grasp all the mechanics.

- The whistle range does not get shown. Its annoying because the whistle range in this edition is huge when fully extended. Also an possible annoyance when playing 2 player (potential funbreaking). As one could tend to whistle all Pikmin away.

- The Pikmin do not glow.

- The captains do not have a colored glowing dot on their antenna which looks a bit silly.

- The flame slugs trail does not show (ok this is mechanic breaking in a visual sense, and a comedy show when you step on invisible fire)

**The end of day screen**
- At the end of a productive day (collected fruit), you can not see the fruit press\fill cannister animation. It is supposed to be rewarding.

There could be other things but those really stand out.

**Comment by iivmok** [comment]
Still a problem

**Comment by IrealiTY** [comment]
Ryujinx crashes periodically, in a non-reproducible way, when playing Pikmin 3 Deluxe. With a `InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.` 

### Log file

[Ryujinx_1.1.244_2022-08-31_23-02-42.log](https://github.com/Ryujinx/Ryujinx/files/9465324/Ryujinx_1.1.244_2022-08-31_23-02-42.log)

### Environment?

- Ryujinx version: 1.1.243</br>
- Game version: 1.1.0</br>

**Comment by EmulationFanatic** [comment]
> Ryujinx crashes periodically, in a non-reproducible way, when playing Pikmin 3 Deluxe. With a `InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.`
> 
> ### Log file
> [Ryujinx_1.1.244_2022-08-31_23-02-42.log](https://github.com/Ryujinx/Ryujinx/files/9465324/Ryujinx_1.1.244_2022-08-31_23-02-42.log)
> 
> ### Environment?
> * Ryujinx version: 1.1.243
> * Game version: 1.1.0

Does this still happen if you disable PPTC?

**Comment by IrealiTY** [comment]
Yes, I tested both, sorry should've mentioned.

**Comment by EmulationFanatic** [comment]
Needs an update. It's possible all of the missing graphical effects are fixed now.

**Comment by NewFurryWorld** [comment]
Voices not working, bug regression.

**Comment by EmulationFanatic** [comment]
> Voices not working, bug regression.

It's noted here in detail.
https://github.com/Ryujinx/Ryujinx/issues/3726

**Comment by JD-The-65th** [comment]
Ryujinx Version 1.1.341
Game Version 1.1.0
Pc: Steam Deck

On the Vulkan renderer, the game crashes when the game displays it's drinking juice animation. Even with PPTC disabled, this issue still occurs. Does not occur on OpenGL. Cannot attach log ATM, I'll see if I can grab it later.

**Comment by EmulationFanatic** [comment]
Needs another update. There have been quite a few fixes recently.

**Comment by B-Crolly** [comment]
As of 1.1.475 - 2022-12-16. Most if not all graphical bugs seem to be fixed. possibly some minor flickering on water, but otherwise looks great. No crashing on juice drinking as mentioned above. However random crashes still persist with Ryujinx.Memory.InvalidMemoryRegionException. 

I've gone as long as 3 in-game days without a crash only for it to crash within 10minutes 3-4 times in a row. Given the daily nature of saving in this game this bug makes it fairly unplayable, unfortunately. Outside of this it runs quite well. The crashes don't appear tied to any in-game activity that I've noticed.

Of note I've tested another emulator that didn't present this instability for pikmin 3 deluxe, so it seems to be specific to ryujinx.

**Comment by ComteNiark** [comment]
Ryujinx Version: 1.1.503
Game Version: 1.1.0
Specs: Ryzen 5 3600, RTX 3060ti, 32gb RAM

Game looks great, a few collision issues in some areas like lilypads and those flowers that bloom when you turn a light on in caves, pikmin can sometimes slip through and fall. Sometimes the pik
[Ryujinx_1.1.503_2023-01-04_05-16-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10341415/Ryujinx_1.1.503_2023-01-04_05-16-58.log)
min get stuck trying to grab something, and sometimes they just stand there and whistling them does nothing, but both these issues are pretty minor (the second one usually resolves itself, they give up on their "task" and become idle), so the game is playable on that front.
The remaining issue is the seemingly random crashes that happen without rhyme or reason. They sometimes happen when a boss loads in, when you pick up something, or just while walking about, so I wouldn't wager a guess as to what causes them. You can sometimes go 5 days without a crash, and then the same day will crash 3 times (which is quite annoying when it happens near nightfall!)

I've included with this post a log of a session that crashed pretty early in gameplay, hope it helps narrow it down.

**Comment by GhostPiggy** [comment]
Ryujinx Version: 1.1.735
Game Version: 1.1.0
Specs: Intel i7-4770, , GTX 1650, 16gb RAM

Haven't experienced any graphical errors I can notice, so far just one or two inconsistent crashes. Seemingly when there are many groups of pikmin split up and performing different tasks, unsure though. Just figured I'd upload a log, if anything else needed can update.

[Ryujinx_1.1.735_2023-04-27_23-18-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11352895/Ryujinx_1.1.735_2023-04-27_23-18-45.log)

**Comment by SixelAlexiS90** [comment]
Ryujinx Version: 1.1.744 though 1.1.750
Game Version: 1.1.0
Specs: Intel i7-4770K, , RTX 2060, 16gb RAM

The halo effect around texts (like the yellow one stating the current mission at the beginning of the day) breaks when using higher internal resolution. Don't know if this affects other graphical effects as well.

Higher internal resolution affects the Depth of Field as well, so with higher resolution the DoF is a bit lighter.

In 10 hours I got around three crashes, first two at the beginning of levels and a third one mid level. I couldn't find a specific reason for the crash since it happened on different occasion and with a different number of Pikmin on stage.

This is a log of one of the crashes tho if it can help:
[Ryujinx_1.1.748_2023-05-04_12-14-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11404943/Ryujinx_1.1.748_2023-05-04_12-14-33.log)

**Comment by Jennifer4444** [comment]
I need help please with my game because whenever I go into a cave my floor gets all white in random places of the map.

**Comment by mrtnptrs** [comment]
> Ryujinx Version: 1.1.744 through 1.1.755 Game Version: 1.1.0 Specs: Intel i7-4770K, , RTX 2060, 16gb RAM
> 
> The halo effect around texts (like the yellow one stating the current mission at the beginning of the day) breaks when using higher internal resolution. Don't know if this affects other graphical effects as well.
> 
> Higher internal resolution affects the Depth of Field as well, so with higher resolution the DoF is a bit lighter.
> 
> In 10 hours I got around three crashes, first two at the beginning of levels and a third one mid level. I couldn't find a specific reason for the crash since it happened on different occasion and with a different number of Pikmin on stage.
> 
> This is a log of one of the crashes tho if it can help: [Ryujinx_1.1.748_2023-05-04_12-14-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11404943/Ryujinx_1.1.748_2023-05-04_12-14-33.log)
> 
> EDIT: got another crash, this one hurt since it was basically at the end of the in-game day... [Ryujinx_1.1.755_2023-05-05_18-46-04.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11408882/Ryujinx_1.1.755_2023-05-05_18-46-04.log)

Do you perhaps have any mods installed? Improper mods and especially mod conflicts can cause the crashes mentioned in your log file, see https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-e-hleguestthread20-cpu-invalidaccesshandler-invalid-memory-access-at-virtual-address-0x0000000000000000-e-hleguestthread20-application--unhandled-exception-caught-ryujinxmemoryinvalidmemoryregionexception-attempted-to-access-an-invalid-memory-region

> I need help please with my game because whenever I go into a cave my floor gets all white in random places of the map.

With you not providing the Ryujinx version, game version, PC-specs, log files, images etc. there is probably not much anyone can do. Additionally, This Ryujinx game compatibility repository is more to report the state of a game and issues a game experiences than expecting a quick magical fix. If the latter is your goal, then your chance of getting it is slim and then it might be more appropriate to ask it on their Discord?

**Comment by SixelAlexiS90** [comment]
@mrtnptrs Hi! No, back when I played I didn't had any mod other than running the game at 2x resolution (maybe 16x anisotropic filtering as well).
My 2060 has 6GB of ram btw.

**Comment by Threxx11** [comment]
Ryujinx version: 1.1.956
Game version: 1.0.1
PC specs:
AMD Ryzen 7 6800H
NVidia 3050Ti Mobile
16 GB DDR5 RAM

Getting an invalid memory access error at random times similar to other people in this thread. No mods or cheats are installed or loaded for the game, and there doesn't seem to be any consistent pattern to the error aside from it seeming to prefer happening later in the game's story. This might just be a fluke however, but I've only tended to encounter it after about Day 10 or so.

Crash log:
[Ryujinx_1.1.956_2023-07-08_00-27-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11988357/Ryujinx_1.1.956_2023-07-08_00-27-49.log)

**Comment by EikoBiko** [comment]
Getting a crash, seemingly caused in relation to using a number of pink pikmin in the twilight forest performing different tasks. Has happened three times, got these logs:

[Ryujinx_1.1.958_2023-07-11_03-14-53.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12011987/Ryujinx_1.1.958_2023-07-11_03-14-53.log)
[Ryujinx_1.1.958_2023-07-11_03-23-48.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12011989/Ryujinx_1.1.958_2023-07-11_03-23-48.log)

Here's my save data if it's useful (keep crashing while trying to bolster my pink pikmin numbers, so it might take a little effort to get a crash):
[save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/12012000/save.zip)

PC Specs:
AMD Ryzen 9 3900X 12-core
16GB RAM
NVIDIA RTX 2080

Was playing at 2x resolution, for what it's worth.

**Comment by limetheskele** [comment]
[Ryujinx_1.1.977_2023-08-07_23-37-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12287110/Ryujinx_1.1.977_2023-08-07_23-37-06.log)

crash while throwing yellow pikmin at electrical line

**Comment by NineKain** [comment]
[Ryujinx_1.1.1160_2024-02-05_23-25-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14172601/Ryujinx_1.1.1160_2024-02-05_23-25-36.log)
crashing when hitting a stick

**Comment by Cyroz** [comment]
Crashes with no obvious cause on Day 3 of Olimar side quests
[Ryujinx_1.1.1385_2024-09-03_02-02-05.log](https://github.com/user-attachments/files/16842040/Ryujinx_1.1.1385_2024-09-03_02-02-05.log)
[Ryujinx_1.1.1385_2024-09-03_00-57-13.log](https://github.com/user-attachments/files/16842041/Ryujinx_1.1.1385_2024-09-03_00-57-13.log)
