### ISSUE TITLE
Arcaea - 0100E680149DC000

### ISSUE THREAD

**Issue by reflexyG** [Ryujinx/Ryujinx-Games-List#3595]
## Game Name
Arcaea - 0100E680149DC000
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
1.0.0
#### Current on `master` :  1.0.6872

*Describe the current game state here.*
White boxes covering texts, images could not display properly and some texture errors.
```
|W| GUI.RenderLoop Gpu GLPERF: DebugSeverityMedium: Buffer performance warning: Buffer object 713 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
```

#### Screenshots :
![image](https://user-images.githubusercontent.com/64774291/118986117-055d7a80-b9ba-11eb-9f23-ec3f3330f190.png)

![image](https://user-images.githubusercontent.com/64774291/118986117-055d7a80-b9ba-11eb-9f23-ec3f3330f190.png)

![image](https://user-images.githubusercontent.com/64774291/118986058-f8d92200-b9b9-11eb-9bff-88072651fd13.png)

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :
[Ryujinx_1.0.6878_2021-05-20_20-11-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6516215/Ryujinx_1.0.6878_2021-05-20_20-11-19.log)

**Comment by EmulationFanatic** [comment]
@reflexyG can you disable openGL logging/any debug logging and include the new log? and make sure to test to see if the issue is fixed, as openGL logging can introduce bugs.

**Comment by reflexyG** [comment]
> @reflexyG can you disable openGL logging/any debug logging and include the new log? and make sure to test to see if the issue is fixed, as openGL logging can introduce bugs.

Disabled openGL logging and debug logging (don't know if I am doing it right), updated ryujinx to 1.0.6883, the issue is still there.

![image](https://user-images.githubusercontent.com/64774291/119037722-4d49c500-b9ed-11eb-8f51-ff7c7e7c593d.png)


Also tried:
- disabling shader cache
- disabling hacks (ignore missing services and expand dram)

Log file:
[Ryujinx_1.0.6883_2021-05-21_04-18-39.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6518346/Ryujinx_1.0.6883_2021-05-21_04-18-39.log)

The screenshot during gameplay that I forgot to upload.

![image](https://user-images.githubusercontent.com/64774291/119037305-c3016100-b9ec-11eb-925a-8b051b4beb9c.png)

expected:
![image](https://user-images.githubusercontent.com/64774291/119037951-8b46e900-b9ed-11eb-817f-897def912e7b.png)

**Comment by reflexyG** [comment]
All Issues mentioned are solved on version 1.0.6890.

**Screenshot**
![image](https://user-images.githubusercontent.com/64774291/119216400-77df6f00-bb0e-11eb-80e4-3a8934a41d3d.png)

![image](https://user-images.githubusercontent.com/64774291/119216429-95143d80-bb0e-11eb-8e61-6bb6b702700e.png)

**Comment by vibe-Chen** [comment]
Game Name

Arcaea - 0100E680149DC000
Game Update Version : 1.0.0c
Current on master : 1.0.6890

Describe the current game state here.
Only half of the game displays as screenshots shown below.

Hardware Specs :
CPU: i5-9300H
GPU: GTX 1660 Ti 6GB (laptop)
RAM: 8+8GB
Screenshots :
![图片](https://user-images.githubusercontent.com/84615342/119217495-2b476400-bb0d-11eb-9825-464427f6f760.png)

**Comment by reflexyG** [comment]
> Game Name
> 
> Arcaea - 0100E680149DC000
> Game Update Version : 1.0.0c
> Current on master : 1.0.6890
> 
> Describe the current game state here.
> Only half of the game displays as screenshots shown below.
> 
> Hardware Specs :
> CPU: i5-9300H
> GPU: GTX 1660 Ti 6GB (laptop)
> RAM: 8+8GB
> Screenshots :
> ![图片](https://user-images.githubusercontent.com/84615342/119217495-2b476400-bb0d-11eb-9825-464427f6f760.png)

Run the game in docked mode.

**Comment by GamerzHell9137** [comment]
All graphical issues related to the game have been fixed by a PR months ago, guess nobody reported it.
![image](https://user-images.githubusercontent.com/2002038/134373143-cfb5bf5b-2a9f-45f6-80b0-a0e5cde63c89.png)

**Comment by ActualMandM** [comment]
The game gets shifted up by half the screen when in portable mode.

![2022-01-24_16-12-12_Ryujinx](https://user-images.githubusercontent.com/15317421/150886655-2018921c-2735-44d8-bc23-6229ff7a10d5.png)

[Ryujinx_1.1.8_2022-01-24_16-13-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7929702/Ryujinx_1.1.8_2022-01-24_16-13-47.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by htps10220** [comment]
The game still gets shifted up by half the screen when in handheld mode.
It only support gamepad in docked mode, so I can't use touchscreen play the game.

**Comment by PolarisPyra** [comment]
Has anyone found a solution to this I just tried my arcaea dump on my steam deck for memes but I cant seem to play handheld (touch mode) with out the bottom half of the screen vanishing. Which basically makes this game only work in controller mode. I was testing using the latest avalon build. It does work flawless in docked how ever.
