### ISSUE TITLE
Splatoon 3 - 0100C2500FC20000

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx-Games-List#4128]
#### Graphics Backend : Vulkan

Game is bootable, doesn't look like there any graphical issues

#### Screenshots :

![image](https://user-images.githubusercontent.com/100526773/198609919-ee638fc3-22a0-4dd6-a152-a3fefa615dca.png)

![image](https://user-images.githubusercontent.com/100526773/198614412-b3547cb3-e569-4603-9ba8-cbbee2876502.png)

![image](https://user-images.githubusercontent.com/100526773/198618310-29dd6451-932b-462f-8a5c-c384448056e9.png)

**Comment by Drako1441** [comment]
how can i dowland de game? I'm new and I don't know. Thanks

**Comment by realNZZN** [comment]
When switching to LAN play, the game resets to plaza and prints this message in the console:
`
00:01:27.904 |I| HLE.OsThread.17 ServicePrepo ProcessReport:
PlayReport log:
 UserId: 00000000000000010000000000000000
 Room: erepo_network_error
 Report: {
    "SectionId": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "SectionType": 0,
    "SectionTime_sec": 69,
    "NetworkType": 2,
    "ServerSessionId": "",
    "P2PSessionId": {
        "TypeCode": 0,
        "Value": "0x0000000000000000"
    },
    "P2PSessionClock_sec": -1,
    "ErrorFrom": "Nifm",
    "ErrorLevel": "NeedSpecialHandling",
    "CommonError": "ReadyNetworkFailed",
    "IsNeedDisplayViewer": False,
    "ApplicationErrorId": 0,
    "system_report_tag": 0
}`

Hardware specs:
Ryujinx 1.1.1-ldn3.0.1 on Windows 11 22H2 22623
CPU: AMD Ryzen 5 3600
GPU: AMD Radeon RX 570 8gb in native Vulkan mode

**Comment by EmulationFanatic** [comment]
> When switching to LAN play, the game resets to plaza and prints this message in the console: ` 00:01:27.904 |I| HLE.OsThread.17 ServicePrepo ProcessReport: PlayReport log: UserId: 00000000000000010000000000000000 Room: erepo_network_error Report: { "SectionId": { "TypeCode": 0, "Value": "0x0000000000000000" }, "SectionType": 0, "SectionTime_sec": 69, "NetworkType": 2, "ServerSessionId": "", "P2PSessionId": { "TypeCode": 0, "Value": "0x0000000000000000" }, "P2PSessionClock_sec": -1, "ErrorFrom": "Nifm", "ErrorLevel": "NeedSpecialHandling", "CommonError": "ReadyNetworkFailed", "IsNeedDisplayViewer": False, "ApplicationErrorId": 0, "system_report_tag": 0 }` ![image](https://user-images.githubusercontent.com/73473573/204096040-3711e6a2-c640-482b-9032-d6162c3f1bdb.png)
> 
> Hardware specs: Ryujinx 1.1.1-ldn3.0.1 on Windows 11 22H2 22623 CPU: AMD Ryzen 5 3600 GPU: AMD Radeon RX 570 8gb in native Vulkan mode

Come to Discord for support.

**Comment by realNZZN** [comment]
> Come to Discord for support.
Posted because its a game-specific issue that hasn't been documented yet

**Comment by EmulationFanatic** [comment]
> > Come to Discord for support.
> 
> Posted because its a game-specific issue that hasn't been documented yet

And that's fine, but all you have to do is disable guest internet access at boot time. Then enable it once in-game.

**Comment by realNZZN** [comment]
> And that's fine, but all you have to do is disable guest internet access at boot time. Then enable it once in-game.

That makes the game bootable, but enabling LAN play ingame doesn't work in any of the LDN builds I've tried since the game's release, though there are screenshots of the LAN play loading screen on the wiki's LDN guide (but no screenshots of the actual LAN play menu that appears after)

**Comment by CoocooFroggy** [comment]
I can reproduce on macOS. Went to Discord for support but there doesn't seem to be a known fix. Us two seem to be the only known cases so far. A moderator told me "maybe it's a mac issue"

@realNZZN are you also on macOS?

**Comment by 81457** [comment]
## Issue Report

#### Game Update Version: v2.0.0

#### Emulator Build Version: 1.1.415

#### Graphics Backend: OpenGL

#### Hardware Specs: 

##### CPU: i7-7700HQ
##### GPU: NVIDIA GTX 1060
##### RAM: 24 GB


The game works and renders correctly for the most part, the issues can be seen in the plaza NPCs, where the hair and skin colors are black, it does also happen with their head accesories.

Selecting an NPC from the plaza renders them black, except for their clothes.

Changing clothes on the equip menu renders the character completly black, including clothes, accesories and weapons.

During matches the character portraits that are shown in the map menu and in the results screen are rendered black as well.

Holograms are also not rendering correctly, they are transparent and only the eyes and the weapons can be seen.

Some Salmon Run enemies are affected by the same rendering issue.

(Multiplayer screenshots are from the previous version of the game (v1.2.1) but the rendering issue is still present in the latest version. (v2.0.0))

#### Screenshots:

<details>
<summary>Details</summary>

![1](https://user-images.githubusercontent.com/27894534/205377810-d24c43f0-ca8a-4ee3-9c3d-6b43d4375cde.PNG)
![2](https://user-images.githubusercontent.com/27894534/205377921-2125edbc-49ea-41df-bf7a-76b18ff3753d.PNG)
![3](https://user-images.githubusercontent.com/27894534/205377938-f28c6e0e-8e7f-42e4-bc31-064e3622311f.PNG)
![4](https://user-images.githubusercontent.com/27894534/205377942-f840c4e3-bd82-42c6-9f3f-11edafc84a8f.PNG)
![5](https://user-images.githubusercontent.com/27894534/205377947-a58b7646-16ec-4f89-9716-ea0e4ef03fd4.PNG)
![6](https://user-images.githubusercontent.com/27894534/205377952-92c58ce5-8a21-4029-b6f7-042ba35f8a45.PNG)
![7](https://user-images.githubusercontent.com/27894534/205377957-8479a382-6aba-40dd-9c0b-80926b8bc0ef.PNG)
![8](https://user-images.githubusercontent.com/27894534/205377966-7b0cde41-28a1-4e29-953a-205875161005.PNG)
![9](https://user-images.githubusercontent.com/27894534/205377978-6399a59f-364d-4fa1-ba11-9abe7513042c.PNG)
![10](https://user-images.githubusercontent.com/27894534/205377984-a84162b7-d909-4a71-8017-e0c8cdcea01d.PNG)
![11](https://user-images.githubusercontent.com/27894534/205377990-3f6d8cd6-e0ff-4ce4-aa42-cb9025bad8b6.PNG)
![12](https://user-images.githubusercontent.com/27894534/205378000-b00e7c1d-7de4-4e57-a85e-c09dd94d16a5.PNG)

</details>


#### Log file:
[Ryujinx_1.1.415_2022-12-02_16-45-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10144067/Ryujinx_1.1.415_2022-12-02_16-45-49.log)

**Comment by EmulationFanatic** [comment]
@81457 Vulkan has better rendering than OpenGL on this game.

**Comment by evanpaul14** [comment]
![ryujinx_cap
[Ryujinx_ 1.1.0-macos1_2022-12-16_19-02-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10250646/Ryujinx_.1.1.0-macos1_2022-12-16_19-02-29.log)
ture_2022-12-16_19-01-28](https://user-images.githubusercontent.com/120766197/208221033-ebf1de8a-d44e-4948-8cfb-70d535145d95.png)
Graphical glitches on m1 mac mini. Only appears from certain angles/locations.

**Comment by 81457** [comment]
## Issue Report

#### Game Update Version: v3.1.1 (+ Inkopolis DLC)

#### Emulator Build Version: 1.1.743

#### Graphics Backend: OpenGL

#### Hardware Specs: 

##### CPU: i7-7700HQ
##### GPU: NVIDIA GTX 1060
##### RAM: 24 GB

#### Details:

When loading the Inkopolis Plaza during the Press ZL+ ZR screen the emulator hangs for some seconds with a Shader linking failed warning in the logs, as the shader doesn't get saved in the cache file, this happens every time the game is booted.

The Shader linking warning does also happen during some Salmon Run events, most specifically Giant Tornado.

Rebuilding the cache from a Vulkan session ends up with some missing shaders in the OpenGL counterpart.

#### Screenshots:

<details>
<summary>Details</summary>

![1](https://user-images.githubusercontent.com/27894534/235796714-8829f4f0-fc9c-417d-b4a5-dcc042e62fb9.PNG)

</details>

#### Log file:
[Ryujinx_1.1.743_2023-05-02_17-41-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11378057/Ryujinx_1.1.743_2023-05-02_17-41-18.log)

**Comment by x4080** [comment]
@evanpaul14 Could you tell what is your config ? Im using m2 pro and it crashed right away using the latest and the original ryujinx

Thanks

**Comment by x4080** [comment]
never mind, using original works

**Comment by calciumista** [comment]
### Splatoon 3

**Game Version:** 4.1.0
**Ryujinx Version:** 1.1.974
**Backend:** OpenGL

Specs:
AMD Ryzen 5 2600
AMD RX570
16GB RAM

Details:
Random shader issues, mostly black and a weird blueish colour.

Screenshots:
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/58620412/a73e217f-6a91-4909-9808-cdbb02f1e06d)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/58620412/aeece6f5-41ce-458c-be10-a1a083d88a6e)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/58620412/da46da8f-f576-452f-b113-79fb4f8c25b2)

Log File
[Ryujinx_1.1.974_2023-08-04_20-14-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12264030/Ryujinx_1.1.974_2023-08-04_20-14-29.log)
:

**Comment by gdkchan** [comment]
Why are you using OpenGL with an AMD graphics card? You should use Vulkan.

**Comment by calciumista** [comment]
> 

Happened on both.

**Comment by BoxBoy12t** [comment]
All skin color is broken on 5.0.0, the inktank also always has no ink shown in it, with some occasional stutters even after shader cache is built. (the last part might just be me.)

4.1.0
![Screenshot 2023-08-30 221812](https://github.com/Ryujinx/Ryujinx-Games-List/assets/99927016/48c538e5-bcee-4bfc-b91c-311dafc4c790)
5.0.0
![Screenshot 2023-08-30 221940](https://github.com/Ryujinx/Ryujinx-Games-List/assets/99927016/4c614041-62be-4d90-b895-2f400aa1753b)

**Comment by mrTerryBogard** [comment]
Good day!

[15.6" Laptop Neobihier ZX-I7-10750H, Intel Core i7-10750H (2.6 GHz), RAM 16 GB, SSD 1024 GB Intel UHD Graphics 630, Windows 11 Pro, Russian keyboard]

Europe, USA, Asia, Japan Version [0100C2500FC20000] [English, Dutch, French, German, Italian, Japanese, Korean, Russian, Chinese, Spanish] (Base Game NSP (3.1GB) + Update 6.0.1 (v1507328) + Wave 1 – Inkopolis DLC (0100C2500FC21065) + Battle Boosting Bonuses DLC (0100C2500FC21064) - 1.1.1100 for Windows 10 & 11 it doesn’t go further than the screen with ink (in previous games there were squids). There is sound and animation. As soon as the Загружено! inscription disappears, that’s it.

**Comment by piplup55** [comment]
Splatoon 3 Side Order Crashes on amd linux on vulkan, opengl is fine

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/100526773/efcc153b-ccef-4751-8c87-87d7ce1ff8dc)

Log file with backend debug logging set to error: [Ryujinx_1.1.1213_2024-02-24_20-32-16.tar.gz](https://github.com/Ryujinx/Ryujinx-Games-List/files/14394404/Ryujinx_1.1.1213_2024-02-24_20-32-16.tar.gz)

**Comment by Azyz-raw** [comment]
Game Update Version: v7.0.0 (+ DLC Wave 1+2 Side Order)

Emulator Build Version: 1.1.1214

Graphics Backend: MoltenVK

Hardware Specs:
MacBookPro M1 - 256GB

RAM: 8 GB

Details:

The 4th floor gameplay mechanics in the latest DLC ( New Order ) aren't working like intended.  
The "Zone" should've been Pink at the start of the floor. And shouldn't get lost that quickly. 

Expected behaviour : 
Pink zone at start 
The player need to ink the zone ( Inking should be easy and straightforward like normal inking in Splatoon ) 
Enemies pop up and can ink the zone with Black ink. If more than 50% is black inked, the Zone is lost. 

Workaround tired : 
I somehow managed to ink the Zone with full pink and the enemy wave popped up but the zone got lost very quickly rendering the stage unplayable. 

Screenshots:


https://github.com/Ryujinx/Ryujinx-Games-List/assets/91022358/5876904a-ee03-46a4-a7c5-c23cb85ba0a5

**Comment by TBV305** [comment]
Game Version: 7.0.0
Ryujinx Version: 1.1.1214
Backend: Vulkan

Specs:
AMD Ryzen 5 5500U
NVIDIA RTX 3050TI
16GB RAM

Details:
Broken lighting in some places [#5](https://github.com/Ryujinx/Ryujinx/issues/5239) 

Screenshots:
Side Order results screen
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/3e64cb87-bbba-4e77-9af5-7a319187163d)
Equip menu
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/710cf1b4-d29d-4f9f-9f46-b55d38101f6a)
ldn 3.1.3 for comparison
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/480e58b4-0784-46f0-82f1-3eba5148d585)

**Comment by Azyz-raw** [comment]
@TBV305 so you're able to go past the 4th floor in New Order. You don't have the bug i just mentioned on Windows. 
I'm trying to figure out its cause, it's something i've never seen before.

**Comment by TBV305** [comment]
1.1.1217
lighting is fixed 
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/2c926269-eba0-4a67-b0a0-5e3cc6346c9b)
@Azyz-raw yes it works fine on windows

**Comment by TBV305** [comment]
1.1.1239
not fixed actually, having flexlion mod menu somehow fixed it?
with mod menu
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/1e108e40-0882-4940-a275-663c2f5ee899)
without
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/b5833b75-a44b-4b26-9f7f-034e0b46f8aa)

**Comment by TBV305** [comment]
1.1.1239
There is a stutter when the game is saving which was not present in previous builds

Noticeable in: 

Starting a run
 Music catching up after a stutter
https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/66411307-c985-43fd-aedb-c0e1f35ceaf1

Resetting a floor
https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/da33f076-9218-43d4-a9d5-c1f62674a09c

Floor cleared
 Music doesn't start until the game is saved
https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/b2b5a472-8f64-43c3-8e25-87d7176f2a71

1.1.1228
Previous build no stutter
https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/fd4271c6-b6b4-4541-870e-877179779cca
https://github.com/Ryujinx/Ryujinx-Games-List/assets/72977924/ce0924f0-f850-47bf-90dc-abde7b948b12

**Comment by CosmicDreamsOfCode** [comment]
> 1.1.1239 not fixed actually, having flexlion mod menu somehow fixed it? with mod menu ![image](https://private-user-images.githubusercontent.com/72977924/313482274-1e108e40-0882-4940-a275-663c2f5ee899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODg0OTksIm5iZiI6MTcxNjQ4ODE5OSwicGF0aCI6Ii83Mjk3NzkyNC8zMTM0ODIyNzQtMWUxMDhlNDAtMDg4Mi00OTQwLWEyNzUtNjYzYzJmNWVlODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDkxOGU0NDI1MTgzYzBkMzNmMTYyMDgxMThkNjU1NzFhYWNjZWNjMjg2Y2VmN2UzNzlkMDYxNzM4NDUwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jsUlfniYH4cGKm7Bopb4xlVduUEb2ucxnqwLfzbGvcI) without ![image](https://private-user-images.githubusercontent.com/72977924/313482256-b5833b75-a44b-4b26-9f7f-034e0b46f8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODg0OTksIm5iZiI6MTcxNjQ4ODE5OSwicGF0aCI6Ii83Mjk3NzkyNC8zMTM0ODIyNTYtYjU4MzNiNzUtYTQ0Yi00YjI2LTlmN2YtMDM0ZTBiNDZmOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NWNmOGY1MzAyMDMyOTRlMGE0MmViM2JkOTYyMzIxMjRmYzkxMGUzOWRiMjJiNGFjZTg2ZDg3YzkyZjI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-FNC2O9GHibzaiF1w-1OAGjJKB39XyXkJ2SPV42VO5o)

Having the mod menu did not fix the issue for me, not sure what happened there. Behaviour of the issue is pretty random though so you could have gotten lucky

**Comment by CosmicDreamsOfCode** [comment]
> > 1.1.1239 not fixed actually, having flexlion mod menu somehow fixed it? with mod menu ![image](https://private-user-images.githubusercontent.com/72977924/313482274-1e108e40-0882-4940-a275-663c2f5ee899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODg0OTksIm5iZiI6MTcxNjQ4ODE5OSwicGF0aCI6Ii83Mjk3NzkyNC8zMTM0ODIyNzQtMWUxMDhlNDAtMDg4Mi00OTQwLWEyNzUtNjYzYzJmNWVlODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDkxOGU0NDI1MTgzYzBkMzNmMTYyMDgxMThkNjU1NzFhYWNjZWNjMjg2Y2VmN2UzNzlkMDYxNzM4NDUwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jsUlfniYH4cGKm7Bopb4xlVduUEb2ucxnqwLfzbGvcI) without ![image](https://private-user-images.githubusercontent.com/72977924/313482256-b5833b75-a44b-4b26-9f7f-034e0b46f8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODg0OTksIm5iZiI6MTcxNjQ4ODE5OSwicGF0aCI6Ii83Mjk3NzkyNC8zMTM0ODIyNTYtYjU4MzNiNzUtYTQ0Yi00YjI2LTlmN2YtMDM0ZTBiNDZmOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NWNmOGY1MzAyMDMyOTRlMGE0MmViM2JkOTYyMzIxMjRmYzkxMGUzOWRiMjJiNGFjZTg2ZDg3YzkyZjI5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-FNC2O9GHibzaiF1w-1OAGjJKB39XyXkJ2SPV42VO5o)
> 
> Having the mod menu did not fix the issue for me, not sure what happened there. Behaviour of the issue is pretty random though so you could have gotten lucky

The issue seems to possibly be fixed by either game version 8.0.0 or latest Ryujinx updates, not sure.

**Comment by User8395** [comment]
I pulled this game from my switch and I keep getting Hash Error

**Comment by TheAgamer554** [comment]
![imagen](https://github.com/Ryujinx/Ryujinx-Games-List/assets/42060301/2acdf9ca-90cd-4446-9b46-21d968e76fee)
Splatoon 3 gets stuck on this screen when Guest Internet Access is turned on, which makes it unable to use LAN play
Using Ryujinx 1.1.1337

**Comment by Azyzraissi** [comment]
You need to launch the game with Guest Internet Access disabled to bypass the loop. 
You can re-enable it when the game is fully launched.

**Comment by Bentheminernz** [comment]
> Game Update Version: v7.0.0 (+ DLC Wave 1+2 Side Order)
> 
> Emulator Build Version: 1.1.1214
> 
> Graphics Backend: MoltenVK
> 
> Hardware Specs: MacBookPro M1 - 256GB
> 
> RAM: 8 GB
> 
> Details:
> 
> The 4th floor gameplay mechanics in the latest DLC ( New Order ) aren't working like intended. The "Zone" should've been Pink at the start of the floor. And shouldn't get lost that quickly.
> 
> Expected behaviour : Pink zone at start The player need to ink the zone ( Inking should be easy and straightforward like normal inking in Splatoon ) Enemies pop up and can ink the zone with Black ink. If more than 50% is black inked, the Zone is lost.
> 
> Workaround tired : I somehow managed to ink the Zone with full pink and the enemy wave popped up but the zone got lost very quickly rendering the stage unplayable.
> 
> Screenshots:
> 
>  SPLATOON3.mp4

I also have this exact same issue on M2 MBA. Annyoing that the Ryujinx devs won't fix it

**Comment by cddude** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/42060301/342941984-2acdf9ca-90cd-4446-9b46-21d968e76fee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTEzODUsIm5iZiI6MTcyMDgxMTA4NSwicGF0aCI6Ii80MjA2MDMwMS8zNDI5NDE5ODQtMmFjZGY5Y2EtOTBjZC00NDQ2LTliNDYtMjFkOTY4ZTc2ZmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE5MDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNGU0MDYxZDAyZDIzMDFlZGU1MjQwYjE0MGIzMjk2ZjlmMjQ1ZTRkNThiM2Y5ZGJiYWM3NmRkN2FkNWRlNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8y32sz3mbBA5ajLuaYYZ3nfEJQFgkK9rHIGUQeoJSI) Splatoon 3 gets stuck on this screen when Guest Internet Access is turned on, which makes it unable to use LAN play Using Ryujinx 1.1.1337

same issue on 1.1.1345

**Comment by CosmicDreamsOfCode** [comment]
![image](https://github.com/user-attachments/assets/3ac0c6da-d2c9-46f5-918b-ac685a9131db)
![image](https://github.com/user-attachments/assets/0721625e-b066-460a-bead-4663df3d95bf)
Latest Ryujinx seems to have issues with water in Alterna. Not sure what version that started with.

**Comment by GamerzHell9137** [comment]
> ![image](https://private-user-images.githubusercontent.com/33284629/351804730-3ac0c6da-d2c9-46f5-918b-ac685a9131db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDc3NjksIm5iZiI6MTcyMTg0NzQ2OSwicGF0aCI6Ii8zMzI4NDYyOS8zNTE4MDQ3MzAtM2FjMGM2ZGEtZDJjOS00NmY1LTkxOGItYWM2ODVhOTEzMWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE4NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Njk0MDRmY2FmNWNkNzkzZThhYjEzZjJjNTE1MmQ5NTZmYzE5ODVlOTkwOWE2NDFiMWMxZTBmMGFkYzNjZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LOwck60oHjWU2myZq0-ondVm3ZHtMpoGYkvb9ITBlSA) ![image](https://private-user-images.githubusercontent.com/33284629/351804823-0721625e-b066-460a-bead-4663df3d95bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NDc3NjksIm5iZiI6MTcyMTg0NzQ2OSwicGF0aCI6Ii8zMzI4NDYyOS8zNTE4MDQ4MjMtMDcyMTYyNWUtYjA2Ni00NjBhLWJlYWQtNDY2M2RmM2Q5NWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE4NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzg4YzY5NjUyMGRhYzQxNzJmY2VkYzgzNGViYjlmNGZkOGU2NjY2ZGE5YWE5OWFkZTgwZjAyYTAzZDUxZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WZzUYAsHC9g9ULb7K_8nlfM-3ClKGf4jXxnU683r_l8) Latest Ryujinx seems to have issues with water in Alterna. Not sure what version that started with.

Drop the log, specs and save, nobody can confirm if its your pc or an issue.

**Comment by TBV305** [comment]
Game Version: 8.0.0
Ryujinx Version: 1.1.1361
Backend: Vulkan

Specs:
AMD Ryzen 5 5500U
NVIDIA RTX 3050 Ti
16GB RAM

Same glitchy water issue

https://github.com/user-attachments/assets/1577838e-ab94-4b94-a0a9-317ff3a8b8de

**Comment by svmoz** [comment]
where do i download this file?

**Comment by davidlb114** [comment]
Can someone explain to me where i can download the game ?
