### ISSUE TITLE
MLB® The Show™ 23 - 0100913019170000

### ISSUE THREAD

**Issue by CrusadingNinja** [Ryujinx/Ryujinx-Games-List#4530]
### Game Name

MLB® The Show™ 23

### Game Update Version

1.0.1

### Emulator Build Version

1.1.687

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 7 3700X*
- ##### GPU: *NVIDIA GTX 1070*
- ##### RAM: *16 GB*

### Game State

Similar issues to its predecessor: https://github.com/Ryujinx/Ryujinx-Games-List/issues/3875
Game renders correctly except for the crowd. Random vertex explosions can occur particularly with player models. 

Game runs up to dynamic 60 FPS but can fluctuate greatly during gameplay. 

Note: There is a known issue in the previous game where NVIDIA Turing and newer GPUs crash on boot with Vulkan. Unsure if this still happens here as I do not have a card to test with. 

### Screenshots

![mlbtheshow23](https://user-images.githubusercontent.com/77567969/228366517-6892d082-6018-425e-87aa-ca461d61b4bd.PNG)

**Comment by victorkok** [comment]
> ### Game Name
> MLB® The Show™ 23
> 
> ### Game Update Version
> 1.0.1
> 
> ### Emulator Build Version
> 1.1.687
> 
> ### Graphics Backend
> OpenGL and Vulkan
> 
> ### Hardware Specs
> * ##### CPU: _Ryzen 7 3700X_
> * ##### GPU: _NVIDIA GTX 1070_
> * ##### RAM: _16 GB_
> 
> ### Game State
> Similar issues to its predecessor: #3875 Crowd is not rendered correctly. Player eyes are not rendered correctly only on OpenGL. Random vertex explosions can occur particularly with player models.
> 
> Game runs up to dynamic 60 FPS but can fluctuate greatly during gameplay.
> 
> Note: There is a known issue in the previous game where NVIDIA Turing and newer GPUs crash on boot with Vulkan. Unsure if this still happens here as I do not have a card to test with.
> 
> ### Screenshots
> ![mlbopengl](https://user-images.githubusercontent.com/77567969/228371303-f6a8232d-b43c-4bdb-9403-46214e2a333e.PNG) ![mlbtheshow23](https://user-images.githubusercontent.com/77567969/228366517-6892d082-6018-425e-87aa-ca461d61b4bd.PNG) ![mlbvertex](https://user-images.githubusercontent.com/77567969/228367087-ab5e5c6f-e7ba-4161-b10b-1d6da7097e46.PNG)
> 
> ### Log File
> _No response_

Still the same with Vulkan in newer Nvidia GPUs, i tested with my GTX 3060, and the game crashes in the loading after the menu, the game only works using OpenGL

**Comment by gperea602** [comment]
somebody wants to work on improving this game ?

**Comment by klais666** [comment]
Pretty sure they are working since the random vertex explosions are fixed.

**Comment by TheGrimReaper798** [comment]
Is Anyone Working on improving the performance in this game?

**Comment by TheGrimReaper798** [comment]
Is anyone gonna fix Vulkan On this Game?

**Comment by Pr0lixCoding** [comment]
Crashes when trying to select teams. 

@
[Ryujinx_1.1.1322_2024-05-25_15-05-27.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15445241/Ryujinx_1.1.1322_2024-05-25_15-05-27.log)

**Comment by TalonVI** [comment]
Running game version 1.0.19 on RTX 2070 Super. There is still an issue running the game using Vulkan on Turing cards. OpenGL is playable but crowd, teeth, and eyes are not rendered. I have not experienced any Vertex explosions. Using Firmware 18.0.0. Willing to provide more details and testing for any devs that look at this. I also own MLB The Show 24 but I have not attempted to emulate it because it's been noted that game still crashes after startup.

**Comment by TalonVI** [comment]
Errors received before crash when using Vulkan.
![image](https://github.com/user-attachments/assets/93302410-f320-48a7-a378-ddef003c5485)
